const baseCenterView= centerView;
centerView=function(){baseCenterView();const toolbar=document.querySelector('.toolbar');if(!toolbar)return;toolbar.querySelector('.toolbar-left')?.insertAdjacentHTML('beforeend','<button class="secondary" id="jobControlLibrary">▣ 作业控件库</button>');toolbar.insertAdjacentHTML('afterend','<div class="business-context"><b>模板上下文</b><span>业务模式：作业计划 / 一件一案</span><span>参数配置统一维护风险、交底与验收标准</span><span>模板仅负责模块拆解、节点编排和填报设计</span></div>');document.querySelector('#jobControlLibrary').onclick=openJobControlLibrary};
function openJobControlLibrary(){const card=document.querySelector('.modal-card');card.className='modal-card job-control-dialog';document.querySelector('#modalBody').innerHTML='<h2>作业控件库</h2><p class="version-intro">作业控件是可复用的业务模块，在流程编排时作为节点表单引用；表单设计页只负责普通字段填报。</p><div class="job-control-list">'+[['风险评估','风险点、管控措施、检测要求、评估签名'],['气体检测','检测项目、检测数值、检测人、检测结果'],['安全措施确认','措施清单、落实状态、确认签名'],['安全交底','作业步骤、防范措施、禁入区域、交底签名'],['接收交底','前序交底内容、接收确认、接收签字'],['结束确认','实际完成时间、结束标准、现场证据、负责人签字'],['验收审批','验收资料、验收意见、验收签名']].map(x=>'<article><div><b>'+x[0]+'</b><span>'+x[1]+'</span></div><button class="ghost">编辑控件</button></article>').join('')+'</div><div class="dialog-footer"><button class="primary" id="closeJobControls">关闭</button></div>';openModalShell();document.querySelector('#closeJobControls').onclick=closeModalShell}
const baseOpenCreateTemplate=openCreateTemplate;
openCreateTemplate=function(){baseOpenCreateTemplate();const form=document.querySelector('.create-form');if(!form)return;form.insertAdjacentHTML('afterbegin','<div class="create-business-hint">先选择业务模式和适用范围，系统会自动载入对应的风险库、安全交底、结束标准和默认流程。</div><label><span><i>*</i>业务模式</span><select id="createBusinessMode"><option>普通作业</option><option>作业计划</option><option>一件一案</option></select></label><label><span>适用作业等级</span><select id="createLevel"><option>未限定</option><option>特级</option><option>一级</option><option>二级</option><option>三级</option></select></label><label><span>标准配置</span><label><input type="checkbox" id="loadStandardConfig" checked> 自动载入参数配置</label></label>');document.querySelector('#createBusinessMode').onchange=e=>state.creation.mode=e.target.value;document.querySelector('#createLevel').onchange=e=>state.creation.level=e.target.value}
const baseOpenDesigner=openDesigner;
openDesigner=function(id){baseOpenDesigner(id);ensureTemplateEditingContext();renderFormBuildStep()}
controlPreview=function(c){if(c.group==='layout')return c.type==='分割线'?'<div class="layout-divider"><span>'+c.name+'</span></div>':'<div class="layout-control"><b>'+c.name+'</b><small>'+c.type+'</small></div>';const special={数字输入:'<span class="fake-input">0　　±</span>',日期选择:'<span class="fake-input">📅 请选择日期</span>',时间选择:'<span class="fake-input">◷ 请选择时间</span>',用户选择:'<span class="fake-input">👤 请选择人员</span>',部门选择:'<span class="fake-input">▦ 请选择部门</span>',下拉选择:'<span class="fake-input select-preview">请选择　⌄</span>',级联选择:'<span class="fake-input select-preview">请选择区域　⌄</span>',单选框组:'<span class="radio-preview"><i></i> 选项一　 <i></i> 选项二</span>',多选框组:'<span class="radio-preview"><i class="check"></i> 选项一　 <i class="check"></i> 选项二</span>',图片上传:'<span class="upload-box">＋ 上传图片</span>',文件上传:'<span class="upload-box">＋ 上传文件</span>',手写签名:'<span class="signature-box">✍ 点击签名</span>',气体检测:'<span class="module-box">气体检测项目　检测结果</span>',风险辨识:'<span class="module-box">风险点　管控措施</span>',安全交底:'<span class="module-box">作业步骤　安全防范措施　签名</span>',子表单:'<span class="subtable-box">明细表　＋ 新增一行</span>'};return '<label class="canvas-field-label"><span>'+(c.required?'<i>*</i>':'')+c.name+'</span>'+(special[c.type]||'<span class="fake-input">'+(c.readonly?'系统自动生成':c.placeholder||'请输入')+'</span>')+'</label>'}
const controlIcons={单行输入:'▣',多行输入:'▤',数字输入:'123',开关:'◉',单选框组:'◉',多选框组:'☑',下拉选择:'⌄',级联选择:'☷',日期选择:'▣',时间选择:'◷',文件上传:'⇧',图片上传:'▧',颜色选择:'●',评分:'☆',滑块:'☷',富文本:'▤',链接:'↗',按钮:'▰',文本:'T',提示:'ⓘ',二维码:'▦',条形码:'▥',组织选择:'♙',岗位选择:'♟',用户选择:'♙',角色选择:'♧',设计子表:'▤',省市区域:'⌖',关联表单:'↔',弹窗选择:'▣',电子签章:'✎',手写签名:'✍',定位:'⌖',Iframe:'□',数字公式:'ƒ',日期公式:'ƒ',关联查询:'⌕',创建人员:'♙',创建时间:'◷',修改人员:'♙',修改时间:'◷',所属组织:'▦',所属岗位:'♟',单据组件:'▤',分组标题:'▤',分割线:'—',折叠面板:'⌄',标签面板:'▥',步骤条:'1→2',栅格容器:'▦',卡片容器:'▣',表格容器:'▤'};
controlLibrary=function(){return controlGroups.filter(g=>g[1]!=='work').map(g=>`<div class="control-group"><button class="group-toggle" data-group-toggle="${g[1]}"><b>${g[0]}</b><span>⌃</span></button><div class="control-grid" data-group-body="${g[1]}">${g[2].map(x=>`<button draggable="true" data-build-control="${x}" data-control-group="${g[1]}"><i class="control-icon">${controlIcons[x]||'◆'}</i><span>${x}</span></button>`).join('')}</div></div>`).join('')}
const baseComponentPropertyMarkup=componentPropertyMarkup;componentPropertyMarkup=function(control){let html=baseComponentPropertyMarkup(control);const extra={开关:'<div class="attribute-section"><b>开关值</b><label>打开时文本<input value="是"></label><label>关闭时文本<input value="否"></label></div>',用户选择:'<div class="attribute-section"><b>选择范围</b><label>数据范围<select><option>全组织</option><option>指定组织</option></select></label></div>',组织选择:'<div class="attribute-section"><b>组织范围</b><select><option>当前组织</option><option>指定组织</option></select></div>',岗位选择:'<div class="attribute-section"><b>岗位范围</b><select><option>当前组织岗位</option><option>全部岗位</option></select></div>',角色选择:'<div class="attribute-section"><b>角色范围</b><select><option>当前组织角色</option><option>全部角色</option></select></div>'};const block=extra[control.type];return block?html.replace('</div></div>',''+block+'</div></div>'):html}
