const briefingSteps=[{stage:'作业前',content:'检查作业人员资质、安全防护设备、个体防护用品、应急救援装备及作业工器具，确定双方监护人员。'},{stage:'作业前',content:'封闭作业区域，在进出口周边设置安全警示标志，对设备、物料和能源介质采取可靠隔离并上锁挂牌。'},{stage:'作业前',content:'对有限空间进行清洗、物料清空、气体置换和通风，作业人员在外部上风侧进行气体检测。'},{stage:'作业中',content:'作业人员在入口处完成进入登记后进入，合理安排作业时间并采取人员轮换。'},{stage:'作业中',content:'作业过程中保持持续通风和气体检测，作业单位、属地单位监护人员全程在岗。'},{stage:'作业后',content:'将全部设备和工具带离有限空间，清点人员和设备，确认无遗留后关闭进出口。'},{stage:'作业后',content:'恢复现场环境，经验收后解除隔离和封闭措施，安全撤离作业现场。'}];
let linkageBriefingType='';
let linkageBriefingLevel='全部';
let linkageFinishType='';
let linkageFinishLevel='全部';
if(workTypeHierarchy===defaultWorkTypeHierarchy)workTypeHierarchy=JSON.parse(JSON.stringify(defaultWorkTypeHierarchy));

function effectiveWorkGroups(){return workTypeHierarchy.filter(group=>Array.isArray(group.children)&&group.children.length>0)}
function persistWorkHierarchy(){try{localStorage.setItem('safeWorkTypeHierarchy',JSON.stringify(workTypeHierarchy))}catch(e){}}

syncWorkTypeConfig=function(){persistWorkHierarchy();configuredWorkTypes().forEach(type=>{if(!riskConfigTypes.includes(type))riskConfigTypes.push(type)});const navGroup=[...document.querySelectorAll('.sidebar .nav-group')].find(x=>x.querySelector('button')?.textContent.includes('作业管理'));if(!navGroup)return;const groups=effectiveWorkGroups();if(!groups.some(x=>x.name===activeWorkGroup))activeWorkGroup=groups[0]?.name||'';navGroup.querySelector('.subnav').innerHTML=groups.map(group=>`<a class="${group.name===activeWorkGroup?'active':''}" href="#" data-view="jobs" data-work-group="${group.name}"><span>•</span>${group.name}</a>`).join('');bindSidebarLinks()};

function singleTypeGroupView(group){const type=group.children[0],matches=[...regularJobs,...jobs].filter(job=>workTypeMatches(job.type,type));return `<div class="page-breadcrumb">作业管理　/　<span>${group.name}</span></div><section class="panel single-work-list"><div class="panel-top"><div><b>${type}</b><small>当前一级节点仅维护 1 个二级作业类型</small></div><div class="list-actions"><button class="ghost single-export">↧ 导出</button><button class="primary" id="applySingleTicket">＋ 申请作业票</button></div></div><div class="filters"><label class="search"><span class="search-icon">⌕</span><input id="singleSearch" placeholder="搜索作业名称、编号或负责人"></label><select id="singleStatus"><option value="">全部状态</option><option>待审批</option><option>执行中</option><option>已完成</option></select><button class="reset" id="singleReset">重置</button></div><div class="table-wrap"><table><thead><tr><th>作业信息</th><th>作业类型 / 等级</th><th>作业区域</th><th>作业时间</th><th>负责人</th><th>当前状态</th><th>操作</th></tr></thead><tbody id="singleRows"></tbody></table></div><footer class="pagination"><span>共 ${matches.length} 条记录</span></footer></section>`}
function setupSingleTypeGroup(group){const type=group.children[0],rows=document.querySelector('#singleRows'),search=document.querySelector('#singleSearch'),status=document.querySelector('#singleStatus'),source=[...regularJobs,...jobs].filter(job=>workTypeMatches(job.type,type));const render=()=>{const q=search.value.trim(),data=source.filter(job=>(!status.value||job.status===status.value)&&(!q||`${job.name}${job.id}${job.owner}`.includes(q)));rows.innerHTML=data.map(job=>`<tr><td><b>${job.name}</b><small>${job.id}</small></td><td>${type}<br><span class="risk low">${job.risk||'一般风险'}</span></td><td>${job.area}</td><td>${job.time}</td><td>${job.owner}</td><td><span class="status ${job.status==='待审批'?'pending':job.status==='执行中'?'running':'done'}">${job.status}</span></td><td><button class="detail single-detail" data-id="${job.id}">查看 ›</button></td></tr>`).join('')||'<tr><td colspan="7" class="empty">暂无该类型作业记录</td></tr>';document.querySelector('.pagination span').textContent=`共 ${data.length} 条记录`};search.oninput=render;status.onchange=render;document.querySelector('#singleReset').onclick=()=>{search.value='';status.value='';render()};document.querySelector('#applySingleTicket').onclick=showNewJob;document.querySelector('.single-export').onclick=()=>toast('导出任务已创建');rows.onclick=e=>{const b=e.target.closest('.single-detail');if(b)showJobDetail(source.find(x=>x.id===b.dataset.id))};render()}

const linkageOpenView=openView;
openView=function(key,nav){if(key!=='jobs')return linkageOpenView(key,nav);document.querySelector('.sidebar a.active')?.classList.remove('active');nav?.classList.add('active');const group=workTypeHierarchy.find(x=>x.name===activeWorkGroup);if(!group||!group.children.length){syncWorkTypeConfig();return toast('请先为一级节点维护二级作业类型')}title.textContent=group.name;subtitle.textContent=`统一管理${group.name}申请、审批、执行与验收全过程`;if(group.children.length===1){content.innerHTML=singleTypeGroupView(group);setupSingleTypeGroup(group)}else{content.innerHTML=jobHome;configureJobGroupPage();const create=document.querySelector('#newJob');if(create)create.textContent='＋ 申请作业票';setupJobs()}setupCommonButtons();document.querySelector('.sidebar').classList.remove('open')};
const linkageSetupWorkTypeTags=setupWorkTypeTags;
setupWorkTypeTags=function(){linkageSetupWorkTypeTags();document.querySelectorAll('.work-type-tags button:not(.more-work-types)').forEach(button=>{const original=button.onclick;button.onclick=event=>{original?.call(button,event);const create=document.querySelector('#newJob');if(create)create.textContent='＋ 申请作业票'}});const create=document.querySelector('#newJob');if(create)create.textContent='＋ 申请作业票'};

workTypeSettingRows=function(){return workTypeHierarchy.map((group,gi)=>`<tbody class="work-type-group"><tr class="work-type-parent" data-group="${gi}"><td>${gi+1}</td><td><b>${group.name}</b><small>一级节点 · ${group.children.length?'已生效':'未生效（请添加二级节点）'}</small></td><td><span class="status ${group.children.length?'done':'pending'}">${group.children.length?'启用':'待配置'}</span></td><td><button class="detail move-work-type" data-direction="up">上移</button><button class="detail move-work-type" data-direction="down">下移</button><button class="detail add-work-child">添加子级</button><button class="detail edit-work-type">编辑</button><button class="danger-text delete-work-type">删除</button></td></tr></tbody>`).join('')};
setupWorkTypeSettings=function(){const table=document.querySelector('.work-type-setting');if(!table)return;table.querySelector('#addWorkTypeGroup').onclick=()=>showWorkTypeDrawer();table.onclick=e=>{const row=e.target.closest('tr');if(!row)return;const gi=+row.dataset.group,child=row.dataset.child===undefined?null:+row.dataset.child;if(e.target.closest('.tree-toggle'))return row.closest('tbody').classList.toggle('collapsed');if(e.target.closest('.move-work-type')){const delta=e.target.closest('.move-work-type').dataset.direction==='up'?-1:1;if(child===null){const to=gi+delta;if(to<0||to>=workTypeHierarchy.length)return;const item=workTypeHierarchy.splice(gi,1)[0];workTypeHierarchy.splice(to,0,item)}else{const children=workTypeHierarchy[gi].children,to=child+delta;if(to<0||to>=children.length)return;const item=children.splice(child,1)[0];children.splice(to,0,item)}syncWorkTypeConfig();document.querySelector('#configBody').innerHTML=generalConfigView();setupConfigActions();return toast('作业类型顺序已更新并同步')}if(e.target.closest('.add-work-child'))return showWorkTypeDrawer(gi);if(e.target.closest('.edit-work-type'))return showWorkTypeDrawer(gi,child,true);if(e.target.closest('.delete-work-type')){if(child===null)workTypeHierarchy.splice(gi,1);else workTypeHierarchy[gi].children.splice(child,1);syncWorkTypeConfig();document.querySelector('#configBody').innerHTML=generalConfigView();setupConfigActions();toast('作业类型配置已删除并同步')}}};

const linkageShowConfigDrawer=showConfigDrawer;
showConfigDrawer=function(titleText,mode,index=null){if(mode!=='level')return linkageShowConfigDrawer(titleText,mode,index);document.querySelector('.config-drawer-layer')?.remove();const types=configuredWorkTypes(),x=index===null?[types[0]||'','','','否','0','0','0']:jobLevelConfigs[index];document.body.insertAdjacentHTML('beforeend',`<div class="config-drawer-layer"><button class="config-drawer-mask"></button><aside class="config-drawer"><header><b>▶ ${titleText}</b><button class="config-drawer-close">×</button></header><div class="config-drawer-body"><label><span><i>*</i> 作业类型</span><select id="cfgType">${types.map(v=>`<option ${v===x[0]?'selected':''}>${v}</option>`).join('')}</select></label><label><span>作业等级</span><input id="cfgLevel" value="${x[1]}" placeholder="请输入作业等级"></label><label><span>定义</span><textarea id="cfgDefinition">${x[2]}</textarea></label></div><footer><button class="ghost config-drawer-cancel">取消</button><button class="primary" id="saveConfigDrawer">确定</button></footer></aside></div>`);const layer=document.querySelector('.config-drawer-layer'),close=()=>layer.remove();layer.querySelector('.config-drawer-mask').onclick=close;layer.querySelector('.config-drawer-close').onclick=close;layer.querySelector('.config-drawer-cancel').onclick=close;layer.querySelector('#saveConfigDrawer').onclick=()=>{const data=[layer.querySelector('#cfgType').value,layer.querySelector('#cfgLevel').value||'—',layer.querySelector('#cfgDefinition').value||'待补充','否','0','0','0'];index===null?jobLevelConfigs.push(data):jobLevelConfigs[index]=data;close();document.querySelector('#configBody').innerHTML=jobLevelConfigView();setupConfigActions();toast('作业等级保存成功')}};

/* 最终树形表格实现：保留配置联动的排序能力，恢复二级节点。 */
workTypeSettingRows=function(){return workTypeHierarchy.map((group,gi)=>{const children=Array.isArray(group.children)?group.children:[];return `<tbody class="work-type-group collapsed"><tr class="work-type-parent" data-group="${gi}" aria-expanded="false"><td><button class="tree-toggle" type="button" aria-label="展开${group.name}二级节点">▶</button>${gi+1}</td><td><b>${group.name}</b><small>一级节点 · ${children.length} 个二级节点</small></td><td><span class="status ${children.length?'done':'pending'}">${children.length?'启用':'待配置'}</span></td><td><button class="detail move-work-type" data-direction="up">上移</button><button class="detail move-work-type" data-direction="down">下移</button><button class="detail add-work-child">添加子级</button><button class="detail edit-work-type">编辑</button><button class="danger-text delete-work-type">删除</button></td></tr>${children.map((child,ci)=>`<tr class="work-type-child" data-group="${gi}" data-child="${ci}"><td>${gi+1}.${ci+1}</td><td><b>${child}</b><small>二级节点</small></td><td><span class="status done">启用</span></td><td><button class="detail move-work-type" data-direction="up">上移</button><button class="detail move-work-type" data-direction="down">下移</button><button class="detail edit-work-type">编辑</button><button class="danger-text delete-work-type">删除</button></td></tr>`).join('')}</tbody>`}).join('')};

setupWorkTypeSettings=function(){const table=document.querySelector('.work-type-setting');if(!table)return;table.querySelector('#addWorkTypeGroup').onclick=()=>showWorkTypeDrawer();table.onclick=e=>{const row=e.target.closest('tr');if(!row)return;const gi=+row.dataset.group,child=row.dataset.child===undefined?null:+row.dataset.child,action=e.target.closest('button:not(.tree-toggle)');if(row.classList.contains('work-type-parent')&&!action){const body=row.closest('tbody'),collapsed=body.classList.toggle('collapsed'),toggle=row.querySelector('.tree-toggle');row.setAttribute('aria-expanded',String(!collapsed));toggle.textContent=collapsed?'▶':'▼';toggle.setAttribute('aria-label',`${collapsed?'展开':'收起'}${workTypeHierarchy[gi].name}二级节点`);return}if(e.target.closest('.move-work-type')){const delta=e.target.closest('.move-work-type').dataset.direction==='up'?-1:1;if(child===null){const to=gi+delta;if(to<0||to>=workTypeHierarchy.length)return;const item=workTypeHierarchy.splice(gi,1)[0];workTypeHierarchy.splice(to,0,item)}else{const children=workTypeHierarchy[gi].children,to=child+delta;if(to<0||to>=children.length)return;const item=children.splice(child,1)[0];children.splice(to,0,item)}syncWorkTypeConfig();document.querySelector('#configBody').innerHTML=generalConfigView();setupConfigActions();return toast('作业类型顺序已更新并同步')}if(e.target.closest('.add-work-child'))return showWorkTypeDrawer(gi);if(e.target.closest('.edit-work-type'))return showWorkTypeDrawer(gi,child,true);if(e.target.closest('.delete-work-type')){if(child===null)workTypeHierarchy.splice(gi,1);else workTypeHierarchy[gi].children.splice(child,1);syncWorkTypeConfig();document.querySelector('#configBody').innerHTML=generalConfigView();setupConfigActions();toast('作业类型配置已删除并同步')}}};

briefingConfigView=function(){const types=configuredWorkTypes();if(!types.includes(linkageBriefingType))linkageBriefingType=types[0]||'';const levels=['全部',...levelsForWorkType(linkageBriefingType)];const rows=(typeof briefingSteps!=='undefined'?briefingSteps:[]).map((x,i)=>`<tr data-index="${i}"><td>${i+1}</td><td>${x.stage}</td><td>${x.content}</td><td><button class="detail briefing-step-edit">编辑</button><button class="danger-text briefing-step-delete">删除</button></td></tr>`).join('')||'<tr><td colspan="4" class="empty">暂无标准化作业步骤</td></tr>';return `<div class="risk-type-tabs config-type-scroll">${types.map(x=>`<button class="${x===linkageBriefingType?'active':''}" data-briefing-type="${x}">${x}</button>`).join('')}</div><div class="briefing-head"><div><b>安全交底预设配置</b><span>维护作业前、作业中、作业后的标准化作业内容</span></div><button class="primary" id="addBriefingStepConfig">＋ 新增作业步骤</button></div><div class="risk-measure-toolbar"><div>${levels.map(x=>`<button class="${x===linkageBriefingLevel?'active':''}" data-briefing-level="${x}">${x}</button>`).join('')}</div></div><div class="table-wrap"><table><thead><tr><th>序号</th><th>作业阶段</th><th>标准化作业内容</th><th>操作</th></tr></thead><tbody id="briefingRows">${rows}</tbody></table></div>`};
finishStandardView=function(){const types=configuredWorkTypes();if(!types.includes(linkageFinishType))linkageFinishType=types[0]||'';const levels=['全部',...levelsForWorkType(linkageFinishType)];if(!levels.includes(linkageFinishLevel))linkageFinishLevel='全部';return `<div class="finish-standard"><div class="risk-type-tabs config-type-scroll">${types.map(x=>`<button class="${x===linkageFinishType?'active':''}" data-finish-type="${x}">${x}</button>`).join('')}</div><div class="briefing-head"><div><b>结束确认标准</b><span>按作业类型和等级维护；“全部”同步到所有等级</span></div><button class="primary" id="addFinish">＋ 新增</button></div><div class="risk-measure-toolbar"><div>${levels.map(x=>`<button class="${x===linkageFinishLevel?'active':''}" data-finish-level="${x}">${x}</button>`).join('')}</div></div><div class="table-wrap"><table><thead><tr><th>序号</th><th>作业类型</th><th>适用等级</th><th>内容</th><th>操作</th></tr></thead><tbody id="finishRows">${finishStandards.filter(x=>x[0]===linkageFinishType).map(x=>{const i=finishStandards.indexOf(x);return `<tr data-index="${i}"><td>${i+1}</td><td>${x[0]}</td><td>${linkageFinishLevel}</td><td>${x[1]}</td><td><button class="detail finish-edit">编辑</button><button class="danger-text finish-delete">删除</button></td></tr>`}).join('')||'<tr><td colspan="5" class="empty">暂无结束确认标准</td></tr>'}</tbody></table></div></div>`};

const linkageSetupAdvancedConfig=setupAdvancedConfig;
setupAdvancedConfig=function(){document.querySelector('#addBriefingStepConfig')?.addEventListener('click',()=>showConfigDrawer('新增作业步骤','briefingStep'));document.querySelector('#briefingRows')?.addEventListener('click',e=>{const row=e.target.closest('tr');if(!row)return;const i=+row.dataset.index;if(e.target.closest('.briefing-step-edit'))showConfigDrawer('编辑作业步骤','briefing',i);if(e.target.closest('.briefing-step-delete')){briefingSteps.splice(i,1);document.querySelector('#configBody').innerHTML=briefingConfigView();setupConfigActions();toast('作业步骤已删除')}});linkageSetupAdvancedConfig();document.querySelectorAll('[data-briefing-type]').forEach(b=>b.onclick=()=>{linkageBriefingType=b.dataset.briefingType;linkageBriefingLevel='全部';document.querySelector('#configBody').innerHTML=briefingConfigView();setupConfigActions()});document.querySelectorAll('[data-briefing-level]').forEach(b=>b.onclick=()=>{linkageBriefingLevel=b.dataset.briefingLevel;document.querySelector('#configBody').innerHTML=briefingConfigView();setupConfigActions();if(linkageBriefingLevel==='全部')toast('当前内容将同步到全部等级')});document.querySelectorAll('[data-finish-type]').forEach(b=>b.onclick=()=>{linkageFinishType=b.dataset.finishType;linkageFinishLevel='全部';document.querySelector('#configBody').innerHTML=finishStandardView();setupConfigActions()});document.querySelectorAll('[data-finish-level]').forEach(b=>b.onclick=()=>{linkageFinishLevel=b.dataset.finishLevel;document.querySelector('#configBody').innerHTML=finishStandardView();setupConfigActions();if(linkageFinishLevel==='全部')toast('当前标准将同步到全部等级')});document.querySelector('#addFinish')?.addEventListener('click',()=>{finishStandards.push([linkageFinishType,'新增结束确认标准，请点击编辑完善内容。']);document.querySelector('#configBody').innerHTML=finishStandardView();setupConfigActions();toast('结束确认标准已新增')});document.querySelector('#finishRows')?.addEventListener('click',e=>{const row=e.target.closest('tr');if(!row)return;const i=+row.dataset.index;if(e.target.closest('.finish-edit'))showConfigDrawer('编辑结束确认标准','finish',i);if(e.target.closest('.finish-delete')){finishStandards.splice(i,1);document.querySelector('#configBody').innerHTML=finishStandardView();setupConfigActions();toast('结束确认标准已删除')}})};

const linkageShowRiskPointDrawer=showRiskPointDrawer;
showRiskPointDrawer=function(index=null){linkageShowRiskPointDrawer(index);if(index===null&&riskConfigState.level==='全部')document.querySelectorAll('[name="riskPointLevel"]').forEach(x=>x.checked=true)};
syncWorkTypeConfig();

const baseConfigDrawerForSteps=showConfigDrawer;
showConfigDrawer=function(titleText,mode,index=null){if(mode!=='briefingStep'&&!(mode==='briefing'&&typeof briefingSteps!=='undefined'&&index!==null))return baseConfigDrawerForSteps(titleText,mode,index);const item=mode==='briefing'?briefingSteps[index]:{stage:'作业前',content:''};document.querySelector('.config-drawer-layer')?.remove();document.body.insertAdjacentHTML('beforeend',`<div class="config-drawer-layer"><button class="config-drawer-mask"></button><aside class="config-drawer"><header><b>▶ ${titleText}</b><button class="config-drawer-close">×</button></header><div class="config-drawer-body"><label><span><i>*</i> 作业阶段</span><select id="stepStage"><option ${item.stage==='作业前'?'selected':''}>作业前</option><option ${item.stage==='作业中'?'selected':''}>作业中</option><option ${item.stage==='作业后'?'selected':''}>作业后</option></select></label><label><span><i>*</i> 标准化作业内容</span><textarea id="stepContent" placeholder="请输入标准化作业内容">${item.content}</textarea></label></div><footer><button class="ghost config-drawer-cancel">取消</button><button class="primary" id="saveStep">确定</button></footer></aside></div>`);const layer=document.querySelector('.config-drawer-layer'),close=()=>layer.remove();layer.querySelector('.config-drawer-mask').onclick=close;layer.querySelector('.config-drawer-close').onclick=close;layer.querySelector('.config-drawer-cancel').onclick=close;layer.querySelector('#saveStep').onclick=()=>{const content=layer.querySelector('#stepContent').value.trim();if(!content)return toast('请输入标准化作业内容');const data={stage:layer.querySelector('#stepStage').value,content};mode==='briefing'?briefingSteps[index]=data:briefingSteps.push(data);close();document.querySelector('#configBody').innerHTML=briefingConfigView();setupConfigActions();toast('安全交底标准化内容已保存')}}
