const regularJobs=[
  {name:'二选车间浓密机年度检修',id:'CG20260819001',type:'维修作业',risk:'一般风险',area:'齐大山铁矿 · 二选车间',time:'08-19 09:00 — 17:30',owner:'张建国',status:'执行中',color:'#27a77a'},
  {name:'破碎站皮带机滚筒更换',id:'CG20260819002',type:'维修作业',risk:'一般风险',area:'大孤山铁矿 · 粗破站',time:'08-19 10:00 — 16:00',owner:'赵海峰',status:'待审批',color:'#27a77a'},
  {name:'选矿配电室设备巡检',id:'CG20260819003',type:'日常检查',risk:'低风险',area:'东鞍山铁矿 · 选矿车间',time:'08-19 08:30 — 11:00',owner:'孙晓辉',status:'已完成',color:'#3979ed'},
  {name:'尾矿库回水泵保养',id:'CG20260819004',type:'设备保养',risk:'一般风险',area:'齐大山铁矿 · 尾矿库',time:'08-19 13:30 — 18:00',owner:'刘志强',status:'待审批',color:'#f39a37'},
  {name:'办公楼消防设施月检',id:'CG20260818012',type:'日常检查',risk:'低风险',area:'矿业公司 · 办公楼',time:'08-18 14:00 — 16:40',owner:'王安全',status:'已完成',color:'#3979ed'}
];
const regularListView=()=>`${cards([['今日常规作业','18','▦','较昨日 +3'],['待我审批','5','⌛','其中 2 项即将超时'],['执行中','7','✓','现场状态正常'],['本月已完成','46','◉','按期完成率 96%']])}<section class="panel"><div class="panel-top"><div class="tabs regular-tabs"><button class="active" data-regular-status="全部">全部作业 <span>18</span></button><button data-regular-status="待审批">待审批 <span>5</span></button><button data-regular-status="执行中">执行中 <span>7</span></button><button data-regular-status="已完成">已完成 <span>6</span></button></div><div class="list-actions"><button class="ghost regular-export">↧ 导出</button><button class="primary" id="newRegular">＋ 新增常规作业</button></div></div><div class="filters"><label class="search">⌕<input id="regularSearch" placeholder="搜索作业名称、编号或负责人"></label><select id="regularType"><option>全部作业类型</option><option>维修作业</option><option>日常检查</option><option>设备保养</option></select><select><option>全部所属单位</option><option>齐大山铁矿</option><option>东鞍山铁矿</option><option>大孤山铁矿</option></select><button class="date">2026-08-19　⌄</button><button class="reset" id="regularReset">重置</button></div><div class="table-wrap"><table><thead><tr><th>作业信息</th><th>作业类型 / 等级</th><th>作业区域</th><th>作业时间</th><th>负责人</th><th>当前状态</th><th>操作</th></tr></thead><tbody id="regularRows"></tbody></table></div><footer class="pagination"><span>共 18 条记录</span><div><button disabled>‹</button><button class="current">1</button><button>2</button><button>3</button><button>›</button></div></footer></section>`;
const regularNav=document.querySelector('[data-view="regular"]');
regularNav.onclick=e=>{e.preventDefault();openRegularList()};
function setRegularShell(pageTitle,pageSubtitle){document.querySelector('.sidebar a.active')?.classList.remove('active');regularNav.classList.add('active');title.textContent=pageTitle;subtitle.textContent=pageSubtitle;document.querySelector('.sidebar').classList.remove('open')}
function openRegularList(){setRegularShell('常规作业','常规检维修作业申请、审批、执行与验收管理');content.innerHTML=regularListView();setupRegularList();setupCommonButtons()}
function setupRegularList(){let status='全部';const render=()=>{const keyword=document.querySelector('#regularSearch').value.trim(),type=document.querySelector('#regularType').value;const data=regularJobs.filter(job=>(status==='全部'||job.status===status)&&(type==='全部作业类型'||job.type===type)&&(!keyword||`${job.name}${job.id}${job.owner}`.includes(keyword)));document.querySelector('#regularRows').innerHTML=data.map(job=>`<tr><td><b>${job.name}</b><small>${job.id}</small></td><td><div class="type"><i class="dot" style="background:${job.color}"></i>${job.type}</div><span class="risk low">${job.risk}</span></td><td>${job.area}</td><td>${job.time}</td><td>${job.owner}</td><td><span class="status ${job.status==='待审批'?'pending':job.status==='执行中'?'running':'done'}">${job.status}</span></td><td><button class="detail regular-detail" data-id="${job.id}">查看 ›</button></td></tr>`).join('')||'<tr><td colspan="7" class="empty">没有找到符合条件的常规作业</td></tr>'};document.querySelector('#newRegular').onclick=openRegularCreate;document.querySelector('#regularSearch').oninput=render;document.querySelector('#regularType').onchange=render;document.querySelector('#regularReset').onclick=()=>{status='全部';document.querySelector('#regularSearch').value='';document.querySelector('#regularType').selectedIndex=0;document.querySelector('.regular-tabs .active')?.classList.remove('active');document.querySelector('.regular-tabs button').classList.add('active');render()};document.querySelectorAll('[data-regular-status]').forEach(button=>button.onclick=()=>{document.querySelector('.regular-tabs .active')?.classList.remove('active');button.classList.add('active');status=button.dataset.regularStatus;render()});document.querySelector('#regularRows').onclick=e=>{const button=e.target.closest('.regular-detail');if(button)showRegularDetail(regularJobs.find(job=>job.id===button.dataset.id))};document.querySelector('.regular-export').onclick=()=>toast('常规作业列表正在导出');render()}
function openRegularCreate(){setRegularShell('新建常规作业','填写作业信息、配置人员与审批流程');content.innerHTML=`<div class="create-page-head"><button class="ghost" id="backRegular">← 返回列表</button><div><b>新建常规作业</b><span>填写完成后提交审批</span></div></div>${regularView()}`;setupRegularWork()}
function showRegularDetail(job){document.querySelector('#modalTitle').textContent='常规作业详情 · '+job.id;document.querySelector('#modalBody').innerHTML=`<div class="modal-grid"><div><span>作业名称</span><b>${job.name}</b></div><div><span>当前状态</span><b>${job.status}</b></div><div><span>作业类型</span><b>${job.type} · ${job.risk}</b></div><div><span>负责人</span><b>${job.owner}</b></div><div><span>作业区域</span><b>${job.area}</b></div><div><span>作业时间</span><b>${job.time}</b></div></div><div class="info-section"><h3>作业说明</h3><p>已完成相关人员、监护设备和审批流程配置，作业过程记录将自动归档。</p></div>`;openModal();document.querySelector('.modal-actions .primary').textContent='查看审批记录'}
function setupRegularWork(){document.querySelector('#backRegular').onclick=openRegularList;document.querySelectorAll('.upload-btn').forEach((button,index)=>button.onclick=()=>{button.nextElementSibling.textContent=index?'常规作业方案.pdf':'现场作业说明.docx';toast('文件上传成功')});document.querySelector('#linkProject').onclick=()=>{document.querySelector('#linkedProject').value='SG202608-012 · 二选车间设备集中检修项目';toast('已关联施工项目')};document.querySelector('#linkTicket').onclick=()=>{document.querySelector('#linkedTicket').value='ZY20260818001 · 二选车间浓密机动火检修';toast('已关联作业票')};document.querySelector('.regular-grid textarea').oninput=e=>e.target.nextElementSibling.textContent=`${e.target.value.length} / 500`;document.querySelector('#addWorker').onclick=()=>{const rows=document.querySelector('#workerRows');rows.insertAdjacentHTML('beforeend',`<tr><td>${rows.children.length+1}</td><td>李作业</td><td>检修工</td><td>设备检修部</td><td>东鞍山烧结厂</td><td><button type="button" class="detail remove-worker">移除</button></td></tr>`);toast('已新增作业人员')};document.querySelector('#workerRows').onclick=e=>{const button=e.target.closest('.remove-worker');if(button){button.closest('tr').remove();[...document.querySelectorAll('#workerRows tr')].forEach((row,index)=>row.children[0].textContent=index+1);toast('作业人员已移除')}};document.querySelector('#cancelRegular').onclick=openRegularList;document.querySelector('#regularWorkForm').onsubmit=e=>{e.preventDefault();toast('常规作业申请已提交审批');setTimeout(openRegularList,700)}}
