const mapPoints=[
 {id:'site-qds',kind:'site',name:'齐大山选矿厂',type:'生产单位',place:'立山区',lng:123.075,lat:41.208,status:'运行正常',risk:'绿色风险',owner:'齐大山铁矿',hazards:2},
 {id:'site-das',kind:'site',name:'东鞍山铁矿',type:'生产单位',place:'千山区',lng:123.105,lat:41.038,status:'运行正常',risk:'绿色风险',owner:'东鞍山铁矿',hazards:1},
 {id:'site-yqs',kind:'site',name:'眼前山铁矿',type:'生产单位',place:'千山区',lng:123.145,lat:40.980,status:'运行正常',risk:'绿色风险',owner:'眼前山铁矿',hazards:0},
 {id:'site-hc',kind:'site',name:'海城市作业区',type:'生产单位',place:'海城市',lng:122.720,lat:40.880,status:'重点关注',risk:'橙色风险',owner:'海城市作业区',hazards:2},
 {id:'DT20260915002',kind:'job',name:'二选车间浓密机动火检修',type:'动火作业',site:'齐大山选矿厂',place:'二选车间',owner:'张建国',status:'作业中',risk:'高风险',lng:123.068,lat:41.201,progress:'风险评估',hazards:2},
 {id:'YX20260918006',kind:'job',name:'-320m 水泵房有限空间检查',type:'有限空间作业',site:'眼前山铁矿',place:'井下泵房',owner:'李明远',status:'申请中',risk:'黄色风险',lng:123.151,lat:40.972,progress:'待审批',hazards:0},
 {id:'GC20260918004',kind:'job',name:'尾矿库回水管道吊装更换',type:'吊装作业',site:'东鞍山铁矿',place:'尾矿库',owner:'刘志强',status:'作业中',risk:'红色风险',lng:123.115,lat:41.028,progress:'现场作业',hazards:1},
 {id:'GD20260920011',kind:'job',name:'粗破站检修平台高处作业',type:'高处作业',site:'齐大山选矿厂',place:'粗破站',owner:'赵海峰',status:'已完成',risk:'绿色风险',lng:123.082,lat:41.214,progress:'验收完成',hazards:0},
 {id:'LD20260923003',kind:'job',name:'选矿配电室临时电源接入',type:'临时用电作业',site:'东鞍山铁矿',place:'选矿车间',owner:'孙晓辉',status:'申请中',risk:'黄色风险',lng:123.098,lat:41.046,progress:'待审批',hazards:1},
 {id:'DH20260924008',kind:'job',name:'破碎车间溜槽补焊',type:'动火作业',site:'眼前山铁矿',place:'破碎车间',owner:'王安全',status:'作业中',risk:'高风险',lng:123.137,lat:40.988,progress:'现场作业',hazards:3},
 {id:'cam-qds-01',kind:'monitor',name:'齐大山布控球 01',type:'视频监控',site:'齐大山选矿厂',place:'二选车间入口',owner:'安全监管部',status:'设备在线',risk:'绿色风险',lng:123.058,lat:41.207,hazards:0},
 {id:'haz-das-01',kind:'hazard',name:'配电箱线缆温度异常',type:'现场隐患',site:'东鞍山铁矿',place:'选矿配电室',owner:'孙晓辉',status:'待整改',risk:'红色风险',lng:123.121,lat:41.041,hazards:1}
];
const workRecords=window.SafetyWorkRecords;
const areas=[...new Set(workRecords.map(item=>item.site))];
mapPoints.splice(4,6,...workRecords.filter(item=>item.lng!==null));
const S='http://www.w3.org/2000/svg',MAP_URL='assets/anshan-210300-full.geojson';
const mapSvg=document.querySelector('#cityMap'),districtLayer=document.querySelector('#districtLayer'),pointLayer=document.querySelector('#pointLayer'),mapStage=document.querySelector('.map-stage'),drawer=document.querySelector('#detailDrawer'),content=document.querySelector('#detailContent'),pointCard=document.querySelector('#mapPointCard');
let geoData,projection,selectedPoint,activeDistrict=null,viewBox={x:0,y:0,w:1000,h:700},dragStart=null;
const coordsOf=g=>g.type==='Polygon'?g.coordinates.flat():g.coordinates.flat(2),project=c=>projection(...c);
function buildProjection(features){const c=features.flatMap(f=>coordsOf(f.geometry)),xs=c.map(p=>p[0]),ys=c.map(p=>p[1]),a=Math.min(...xs),b=Math.max(...xs),d=Math.min(...ys),e=Math.max(...ys),pad=58,k=Math.min((1000-2*pad)/(b-a),(700-2*pad)/(e-d));return(x,y)=>[pad+(x-a)*k,700-pad-(y-d)*k]}
function pathOf(g){const polys=g.type==='Polygon'?[g.coordinates]:g.coordinates;return polys.map(p=>p.map(r=>r.map((c,i)=>{const[x,y]=project(c);return`${i?'L':'M'}${x.toFixed(1)},${y.toFixed(1)}`}).join('')+'Z').join('')).join('')}
function boundsOf(f){const p=coordsOf(f.geometry).map(project),x=p.map(v=>v[0]),y=p.map(v=>v[1]),a=Math.min(...x),b=Math.min(...y),w=Math.max(...x)-a,h=Math.max(...y)-b,q=Math.max(w,h)*.1;return{x:a-q,y:b-q,w:w+2*q,h:h+2*q}}
function setView(box,moving=true){const zoomChanged=viewBox.w!==box.w||viewBox.h!==box.h;viewBox=box;if(moving)mapSvg.classList.add('moving');mapSvg.setAttribute('viewBox',`${box.x} ${box.y} ${box.w} ${box.h}`);mapSvg.dispatchEvent(new CustomEvent('gis:viewchange',{detail:{zoomChanged}}));setTimeout(()=>mapSvg.classList.remove('moving'),360)}
function renderDistricts(){districtLayer.innerHTML='';geoData.features.forEach(f=>{const g=document.createElementNS(S,'g'),p=document.createElementNS(S,'path'),t=document.createElementNS(S,'text'),c=f.properties.centroid||f.properties.center,[x,y]=project(c);g.classList.add('district-shape');g.dataset.code=f.properties.adcode;g.setAttribute('aria-label',`双击进入${f.properties.name}`);p.setAttribute('d',pathOf(f.geometry));t.setAttribute('x',x);t.setAttribute('y',y);t.textContent=f.properties.name;g.append(p,t);g.onmouseenter=()=>g.classList.add('hover');g.onmouseleave=()=>g.classList.remove('hover');g.ondblclick=e=>{e.preventDefault();e.stopPropagation();drill(f)};districtLayer.append(g)})}
function inRing(p,r){let hit=false;for(let i=0,j=r.length-1;i<r.length;j=i++){const[a,b]=r[i],[c,d]=r[j];if((b>p[1])!==(d>p[1])&&p[0]<(c-a)*(p[1]-b)/(d-b)+a)hit=!hit}return hit}
function inFeature(p,f){const ps=f.geometry.type==='Polygon'?[f.geometry.coordinates]:f.geometry.coordinates;return ps.some(x=>inRing(p,x[0]))}
function visible(p){const q=document.querySelector('#mapSearch').value.trim(),t=document.querySelector('#typeFilter').value,s=document.querySelector('#statusFilter').value;if(q&&!`${p.name}${p.id}${p.site||''}`.includes(q)||t!=='all'&&p.type!==t||s!=='all'&&p.status!==s)return false;if(activeDistrict){const f=geoData.features.find(x=>String(x.properties.adcode)===activeDistrict);if(f&&!inFeature([p.lng,p.lat],f))return false}return true}
function renderPoints(){pointCard.hidden=true;pointLayer.innerHTML='';mapPoints.filter(visible).forEach(p=>{const[x,y]=project([p.lng,p.lat]),g=document.createElementNS(S,'g'),h=document.createElementNS(S,'circle'),c=document.createElementNS(S,'circle'),t=document.createElementNS(S,'text');g.classList.add('gis-point',p.kind,p.status.includes('作业中')?'working':p.status.includes('申请')||p.status.includes('待')?'pending':'finished');g.setAttribute('transform',`translate(${x} ${y})`);g.setAttribute('role','button');g.setAttribute('tabindex','0');g.setAttribute('aria-label',`查看${p.name}`);h.setAttribute('r',16);h.classList.add('point-halo');c.setAttribute('r',p.kind==='site'?8:6);t.setAttribute('x',12);t.setAttribute('y',4);t.textContent=p.name;g.append(h,c,t);g.addEventListener('click',e=>{e.stopPropagation();showPointCard(p,e)});g.addEventListener('keydown',e=>{if(e.key==='Enter')showPointCard(p,{clientX:mapStage.getBoundingClientRect().left+mapStage.clientWidth/2,clientY:mapStage.getBoundingClientRect().top+mapStage.clientHeight/2})});pointLayer.append(g)})}
function showPointCard(point,event){selectedPoint=point;const stage=mapStage.getBoundingClientRect(),x=event.clientX-stage.left,y=event.clientY-stage.top;pointCard.style.left=`${x}px`;pointCard.style.top=`${Math.max(115,Math.min(stage.height-105,y))}px`;pointCard.classList.toggle('flip',x>stage.width-275);document.querySelector('#pointCardKind').textContent=point.kind==='job'?'作业点位':point.kind==='site'?'生产单位':point.kind==='monitor'?'监控设备':'隐患点位';document.querySelector('#pointCardTitle').textContent=point.name;document.querySelector('#pointCardMeta').textContent=`${point.type} · ${point.site||point.place} · ${point.owner}`;document.querySelector('#pointCardStatus').textContent=point.status;pointCard.hidden=false}
function drill(f){activeDistrict=String(f.properties.adcode);document.querySelector('#mapBack').hidden=false;document.querySelector('#mapLevel').textContent=`鞍山市 / ${f.properties.name} · 区县视图`;districtLayer.querySelectorAll('g').forEach(g=>g.classList.toggle('is-hidden',g.dataset.code!==activeDistrict));setView(boundsOf(f));renderPoints()}
function cityView(){activeDistrict=null;document.querySelector('#mapBack').hidden=true;document.querySelector('#mapLevel').textContent='鞍山市 · 市级视图';districtLayer.querySelectorAll('g').forEach(g=>g.classList.remove('is-hidden'));setView({x:0,y:0,w:1000,h:700});renderPoints()}
async function loadMap(){try{const r=await fetch(MAP_URL);if(!r.ok)throw 0;geoData=await r.json();projection=buildProjection(geoData.features);renderDistricts();renderPoints();document.querySelector('#mapLoading').hidden=true}catch(e){document.querySelector('#mapLoading').innerHTML='鞍山市 GIS 边界加载失败<br><button onclick="location.reload()">重新加载</button>'}}
mapStage.addEventListener('wheel',e=>{e.preventDefault();pointCard.hidden=true;if(!geoData)return;const r=mapSvg.getBoundingClientRect(),mx=viewBox.x+(e.clientX-r.left)/r.width*viewBox.w,my=viewBox.y+(e.clientY-r.top)/r.height*viewBox.h,f=e.deltaY>0?1.16:.86,w=Math.max(80,Math.min(1400,viewBox.w*f)),h=w*.7,rx=(mx-viewBox.x)/viewBox.w,ry=(my-viewBox.y)/viewBox.h;setView({x:mx-rx*w,y:my-ry*h,w,h},false)},{passive:false});
mapStage.addEventListener('dblclick',e=>{const group=e.target.closest('.district-shape');if(!group||!geoData)return;e.preventDefault();e.stopImmediatePropagation();const feature=geoData.features.find(f=>String(f.properties.adcode)===group.dataset.code);if(feature)drill(feature)},true);
mapSvg.onpointerdown=e=>{if(e.target.closest('.gis-point,.gis-cluster,.area-zone,.district-shape'))return;dragStart={x:e.clientX,y:e.clientY,box:{...viewBox}};mapSvg.setPointerCapture(e.pointerId)};mapSvg.onpointermove=e=>{if(!dragStart)return;const r=mapSvg.getBoundingClientRect(),dx=(e.clientX-dragStart.x)/r.width*viewBox.w,dy=(e.clientY-dragStart.y)/r.height*viewBox.h;setView({...dragStart.box,x:dragStart.box.x-dx,y:dragStart.box.y-dy},false)};mapSvg.onpointerup=mapSvg.onpointercancel=()=>dragStart=null;
function baseDetail(p){const coordinate=p.lng==null?'坐标缺失，未生成地图点位':`${p.lng.toFixed(4)}, ${p.lat.toFixed(4)}`;return `<section class="detail-card"><h3>${p.kind==='site'?'点位信息':'基本信息'}</h3><dl><dt>点位编号</dt><dd>${p.id}</dd><dt>名称</dt><dd>${p.name}</dd><dt>数据类型</dt><dd>${p.type}</dd><dt>所属位置</dt><dd>${p.site||p.place} · ${p.place}</dd><dt>负责人/单位</dt><dd>${p.owner}</dd><dt>当前状态</dt><dd><em>${p.status}</em></dd><dt>GIS 坐标</dt><dd>${coordinate}</dd></dl></section><section class="detail-card"><h3>实时进度</h3><div class="steps"><i class="done">申请</i><i class="done">审批</i><i class="active">作业执行</i><i>验收</i></div></section>`}
function monitor(p){return `<section class="detail-card"><h3>实时监控视频 <span>● 设备在线</span></h3><div class="video-placeholder"><i>▶</i><b>${p.place} · 布控球 01</b><span>原型演示画面</span></div></section><section class="detail-card"><h3>环境监测数据 <time>14:42:26</time></h3><div class="gauges"><article><b>20.8</b><span>O₂ %VOL</span></article><article><b>0</b><span>CO ppm</span></article><article><b>26.4</b><span>温度 ℃</span></article><article><b>48</b><span>湿度 %</span></article></div></section>`}
function hazards(p){return `<section class="detail-card hazard-summary"><h3>隐患概况</h3><div><article><b>${p.hazards}</b><span>当前隐患</span></article><article><b>${Math.max(0,p.hazards-1)}</b><span>待整改</span></article><article><b>${p.hazards?1:0}</b><span>已复查</span></article></div></section>${p.hazards?`<section class="detail-card"><article class="hazard-item"><header><em>高危</em><time>14:28</time></header><b>${p.kind==='hazard'?p.name:'作业区域警示标识缺失'}</b><p>责任人：${p.owner}　整改时限：今日 16:00</p></article></section>`:'<div class="empty-state"><i>✓</i><b>暂无隐患数据</b></div>'}`}
function openDetail(p){selectedPoint=p;drawer.classList.add('open');drawer.setAttribute('aria-hidden','false');document.querySelector('#detailRisk').textContent=p.risk;document.querySelector('#detailRisk').className=p.risk.includes('红')?'red':p.risk.includes('黄')?'yellow':'green';drawer.querySelectorAll('nav button').forEach((b,i)=>b.classList.toggle('active',i===0));content.innerHTML=baseDetail(p)}
drawer.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{drawer.querySelector('nav .active').classList.remove('active');b.classList.add('active');content.innerHTML=b.dataset.tab==='job'?baseDetail(selectedPoint):b.dataset.tab==='monitor'?monitor(selectedPoint):hazards(selectedPoint)});document.querySelector('#closeDetail').onclick=()=>drawer.classList.remove('open');document.querySelector('#mapBack').onclick=cityView;document.querySelectorAll('#mapSearch,#typeFilter,#statusFilter').forEach(e=>e.addEventListener(e.tagName==='INPUT'?'input':'change',renderPoints));document.querySelector('#fullscreenBtn').onclick=()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen();
document.querySelector('#pointCardClose').onclick=e=>{e.stopPropagation();pointCard.hidden=true};document.querySelector('#pointCardDetail').onclick=e=>{e.stopPropagation();pointCard.hidden=true;openDetail(selectedPoint)};
const listDrawer=document.querySelector('#workListDrawer'),listContent=document.querySelector('#workListContent'),listSearch=document.querySelector('#workListSearch');let currentList=[];
function recordsFor(key){if(key==='全部作业')return workRecords;if(['危险作业','危大工程','交叉作业'].includes(key))return workRecords.filter(x=>x.category===key);if(['申请中','作业中','已暂停','已完成'].includes(key))return workRecords.filter(x=>x.status===key);if(['待审批','待监管确认','待验收'].includes(key))return workRecords.filter(x=>x.flow===key);if(key==='本周计划')return workRecords.filter(x=>x.plan===key);if(['已关联作业票','待发起作业'].includes(key))return workRecords.filter(x=>x.ticket===key);return workRecords.filter(x=>x.type===key)}
function renderWorkList(){const q=listSearch.value.trim(),rows=currentList.filter(x=>!q||`${x.name}${x.id}${x.owner}`.includes(q));document.querySelector('#workListCount').textContent=`${rows.length} 项`;listContent.innerHTML=rows.length?rows.map(x=>`<article class="work-list-row" data-id="${x.id}"><span>${x.id}</span><div><b>${x.name}</b><small>${x.type} · ${x.site}</small></div><em>${x.status}</em><button>查看详情</button></article>`).join(''):'<div class="work-list-empty"><b>暂无匹配作业</b><span>请调整搜索条件</span></div>';listContent.querySelectorAll('.work-list-row button').forEach(b=>b.onclick=()=>{const x=workRecords.find(r=>r.id===b.closest('article').dataset.id);listDrawer.classList.remove('open');listDrawer.setAttribute('aria-hidden','true');openDetail(x)})}
function openWorkList(key){currentList=recordsFor(key);document.querySelector('#workListTitle').textContent=`${key}列表`;listSearch.value='';renderWorkList();listDrawer.classList.add('open');listDrawer.setAttribute('aria-hidden','false')}
document.querySelectorAll('[data-work-list]').forEach(b=>b.onclick=()=>openWorkList(b.dataset.workList));document.querySelector('#closeWorkList').onclick=()=>{listDrawer.classList.remove('open');listDrawer.setAttribute('aria-hidden','true')};listSearch.oninput=renderWorkList;
function clock(){const d=new Date(),p=n=>String(n).padStart(2,'0');document.querySelector('#clock').textContent=`${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())} ${p(d.getHours())}:${p(d.getMinutes())}:${p(d.getSeconds())}`;document.querySelector('#weekday').textContent=['星期日','星期一','星期二','星期三','星期四','星期五','星期六'][d.getDay()]};clock();setInterval(clock,1000);loadMap();
