const baseCenterView= centerView;
centerView=function(){baseCenterView();const toolbar=document.querySelector('.toolbar');if(!toolbar)return;toolbar.querySelector('.toolbar-left')?.insertAdjacentHTML('beforeend','<button class="secondary" id="jobControlLibrary">▣ 作业控件库</button>');toolbar.insertAdjacentHTML('afterend','<div class="business-context"><b>模板上下文</b><span>业务模式：作业计划 / 一件一案</span><span>参数配置统一维护风险、交底与验收标准</span><span>模板仅负责模块拆解、节点编排和填报设计</span></div>');document.querySelector('#jobControlLibrary').onclick=renderConfiguredControlLibrary};
function openJobControlLibrary(){const card=document.querySelector('.modal-card');card.className='modal-card job-control-dialog';document.querySelector('#modalBody').innerHTML='<h2>作业控件库</h2><p class="version-intro">作业控件是可复用的业务模块，在流程编排时作为节点表单引用；表单设计页只负责普通字段填报。</p><div class="job-control-list">'+[['风险评估','风险点、管控措施、检测要求、评估签名'],['气体检测','检测项目、检测数值、检测人、检测结果'],['安全措施确认','措施清单、落实状态、确认签名'],['安全交底','作业步骤、防范措施、禁入区域、交底签名'],['接收交底','前序交底内容、接收确认、接收签字'],['结束确认','实际完成时间、结束标准、现场证据、负责人签字'],['验收审批','验收资料、验收意见、验收签名']].map(x=>'<article><div><b>'+x[0]+'</b><span>'+x[1]+'</span></div><button class="ghost job-control-edit" data-control-name="'+x[0]+'">编辑控件</button></article>').join('')+'</div><div class="dialog-footer"><button class="primary" id="closeJobControls">关闭</button></div>';openModalShell();document.querySelector('#closeJobControls').onclick=closeModalShell;document.querySelectorAll('.job-control-edit').forEach(b=>b.onclick=()=>showJobControlEditor(b.dataset.controlName))}
function showJobControlEditor(name){const card=document.querySelector('.modal-card');document.querySelector('#modalBody').innerHTML='<h2>编辑控件 · '+name+'</h2><p class="version-intro">维护该业务控件在流程节点中的展示说明和配置要求。</p><label class="control-editor-field"><span>控件说明</span><textarea id="jobControlDescription" placeholder="请输入控件说明"></textarea></label><label class="control-editor-field"><span>是否必填</span><select id="jobControlRequired"><option>是</option><option>否</option></select></label><div class="dialog-footer"><button class="ghost" id="backJobControls">返回控件库</button><button class="primary" id="saveJobControl">保存</button></div>';document.querySelector('#backJobControls').onclick=openJobControlLibrary;document.querySelector('#saveJobControl').onclick=()=>{toast('控件配置已保存');openJobControlLibrary()}}
const jobControlNames=['风险评估','气体检测','安全措施确认','安全交底','接收交底','结束确认','验收审批'];
const baseJobControlLibrary=openJobControlLibrary;
openJobControlLibrary=function(){baseJobControlLibrary();document.querySelectorAll('.job-control-edit').forEach((b,i)=>{b.textContent='查看样式';b.onclick=()=>openJobControlPreview(b.dataset.controlName||jobControlNames[i])})};
function openJobControlPreview(name){const previews={风险评估:'风险点选择 · 管控措施 · 评估签名',气体检测:'检测人员 · 检测频次 · 气体项目 · 检测结果',安全措施确认:'安全措施清单 · 已落实 / 不涉及 · 确认签名',安全交底:'作业步骤 · 安全防范措施 · 禁入区域 · 交底签名',接收交底:'作业基本信息 · 风险管控 · 接收确认 · 接收签字',结束确认:'实际开始/完成时间 · 结束标准 · 现场证据',验收审批:'验收资料 · 验收意见 · 验收签名'};document.querySelector('#modalBody').innerHTML='<h2>'+name+' · 样式预览</h2><p class="version-intro">控件库仅展示标准组件样式；具体字段、权限和是否启用在流程节点中配置。</p><div class="job-preview-form"><div class="preview-section"><b>'+name+'</b><span>'+previews[name]+'</span></div><div class="preview-row"><label>示例字段</label><div class="preview-placeholder">请在流程节点中配置</div></div><div class="preview-row"><label>签名 / 附件</label><div class="preview-sign">✍ 点击签名　　＋ 上传附件</div></div></div><div class="dialog-footer"><button class="primary" id="backJobPreview">返回控件库</button></div>';document.querySelector('#backJobPreview').onclick=openJobControlLibrary}
const baseBindCenter=bindCenter;
bindCenter=function(){baseBindCenter();document.querySelectorAll('[data-more]').forEach(b=>b.onclick=()=>openTemplateActions(b.dataset.more))};
function openTemplateActions(id){document.querySelector('.template-actions-popover')?.remove();const card=document.querySelector('[data-more="'+id+'"]')?.closest('.template-card');if(!card)return;const pop=document.createElement('div');pop.className='template-actions-popover';pop.innerHTML='<button data-template-copy>复制</button><button data-template-disable>停用</button><button class="danger-text" data-template-delete>删除</button>';card.appendChild(pop);pop.querySelector('[data-template-copy]').onclick=()=>{const source=templates.find(t=>t.id===id);const copy={...source,id:id+'-copy-'+Date.now(),name:source.name+'副本',code:source.code+'-COPY',status:'草稿',updated:'2026-09-07'};templates.unshift(copy);pop.remove();centerView();toast('已复制为草稿模板')};pop.querySelector('[data-template-disable]').onclick=()=>{const t=templates.find(t=>t.id===id);if(t){t.status='草稿';pop.remove();centerView();toast('模板已停用并转为草稿')}};pop.querySelector('[data-template-delete]').onclick=()=>{const t=templates.find(t=>t.id===id);if(t?.activeRecords){toast('该模板下有申请中或作业中的记录，暂不能删除');return}templates.splice(templates.findIndex(t=>t.id===id),1);pop.remove();centerView();toast('模板已删除')};setTimeout(()=>document.addEventListener('click',function close(e){if(!pop.contains(e.target)&&!e.target.closest('[data-more]')){pop.remove();document.removeEventListener('click',close)}}),0)}
const baseCreateTemplateWithTypes=openCreateTemplate;
openCreateTemplate=function(){baseCreateTemplateWithTypes();const select=document.querySelector('#createCategory');if(!select)return;let configured=[];try{configured=JSON.parse(localStorage.getItem('safeWorkTypeHierarchy')||'[]')}catch(e){}const types=configured.flatMap(x=>(x.children||[]).map(y=>typeof y==='string'?y:y.name)).filter(Boolean);if(types.length){select.innerHTML=types.map(x=>'<option>'+x+'</option>').join('');state.creation.category=types[0]}}
const normalizeDesignerHeader=()=>{document.querySelector('#versionRecords')?.remove();document.querySelector('.template-context-strip')?.remove();document.querySelector('.workflow-status')?.remove();document.querySelector('#backCenter')?.remove();document.querySelector('.designer-head h2 .tag')?.remove();const meta=document.querySelector('.designer-head h2')?.parentElement?.querySelector('p');if(meta)meta.remove();const titleEl=document.querySelector('#pageTitle'),subEl=document.querySelector('#pageSubtitle');if(titleEl){titleEl.textContent='';titleEl.style.display='none'}if(subEl){subEl.textContent='';subEl.style.display='none'}const test=document.querySelector('#testTemplate');if(test)test.textContent='▷ 流程测试';if(state.mode==='flow'){const actions=document.querySelector('.designer-actions'),strip=document.querySelector('.wizard-strip');if(actions&&strip&&!strip.contains(actions))strip.appendChild(actions);if(!document.querySelector('#flowPrev'))actions?.insertAdjacentHTML('afterbegin','<button class="ghost" id="flowPrev">上一步</button>');document.querySelector('#flowPrev')?.addEventListener('click',renderListBuildStep)}};
const previousRenderDesigner=renderDesigner;renderDesigner=function(){previousRenderDesigner();normalizeDesignerHeader()};
const previousCenterView=centerView;centerView=function(){previousCenterView();const titleEl=document.querySelector('#pageTitle'),subEl=document.querySelector('#pageSubtitle');if(titleEl)titleEl.style.display='';if(subEl)subEl.style.display=''};
const previousRenderPublishStep=renderPublishStep;renderPublishStep=function(){previousRenderPublishStep();document.querySelectorAll('.release-config label').forEach(label=>{if(label.textContent.includes('保留当前草稿版本'))label.remove()})};
const previousRenderListBuildStep=renderListBuildStep;renderListBuildStep=function(){previousRenderListBuildStep();const box=document.querySelector('.list-config');if(box&&!box.querySelector('.list-help'))box.insertAdjacentHTML('afterbegin','<div class="list-help"><b>展示设计说明</b><p>配置作业台的列表筛选项、搜索项、展示字段和操作入口。</p><p><strong>高级查询</strong>：支持按多个字段、时间范围和作业状态组合筛选。</p><p><strong>分页与字段权限</strong>：控制每页数据量，并按角色隐藏或显示列表字段。</p></div>')};
document.addEventListener('click',event=>{const button=event.target.closest('[data-settings-view]');if(button&&typeof renderResourceStep==='function'){event.preventDefault();renderResourceStep(button.dataset.settingsView)}});
const baseOpenCreateTemplate=openCreateTemplate;
openCreateTemplate=function(){baseOpenCreateTemplate();const form=document.querySelector('.create-form');if(!form)return;let groups=[];try{groups=JSON.parse(localStorage.getItem('safeWorkTypeHierarchy')||'[]')}catch(e){}groups=groups.filter(g=>g&&g.name);if(!groups.length)groups=[{name:'常规作业',children:['常规作业']},{name:'危险作业',children:['有限空间作业','高处作业','吊装作业','临时用电作业','动火作业','动土作业','断路作业','盲板抽堵作业','爆破作业（井下）','爆破作业（露天）']},{name:'交叉作业',children:['交叉作业模板作业']},{name:'危大工程',children:['基坑作业','脚手架作业','模板作业','拆除工程作业','起重吊装及起重机械安装拆卸作业']}];const category=document.querySelector('#createCategory'),nameLabel=document.querySelector('#createName')?.closest('label');if(category&&nameLabel){const nameInput=document.querySelector('#createName');const categoryLabel=category.closest('label');const names=groups.flatMap(g=>g.children||[]).map(x=>typeof x==='string'?x:x.name).filter(Boolean);category.innerHTML=groups.map((g,i)=>`<option value="${g.name}">${g.name}</option>`).join('');nameLabel.innerHTML='<span><i>*</i>模板名称</span><select id="createName"></select>';const nameSelect=document.querySelector('#createName');const syncNames=()=>{const group=groups.find(g=>g.name===category.value)||groups[0],children=(group.children||[]).map(x=>typeof x==='string'?x:x.name).filter(Boolean);nameSelect.innerHTML=children.map(x=>`<option value="${x}">${x}</option>`).join('');state.creation.category=group.name;state.creation.name=nameSelect.value||'';const code=document.querySelector('#createCode'),url=document.querySelector('#createUrl');if(code&&!code.dataset.manual){state.creation.code=makeTemplateCode(state.creation.name);code.value=state.creation.code}if(url){state.creation.url=state.creation.code?`${location.origin}/#/work-templates/${state.creation.code.toLowerCase()}`:'';url.value=state.creation.url}};category.onchange=syncNames;nameSelect.onchange=syncNames;syncNames();form.insertBefore(categoryLabel,nameLabel)}form.insertAdjacentHTML('afterbegin','<div class="create-business-hint">先选择参数配置中的作业分类和模板名称，系统会自动载入对应的风险库、安全交底、结束标准和默认流程。</div><label><span><i>*</i>业务模式</span><select id="createBusinessMode"><option>普通作业</option><option>作业计划</option><option>一件一案</option></select></label><label><span>适用作业等级</span><select id="createLevel"><option>未限定</option><option>特级</option><option>一级</option><option>二级</option><option>三级</option></select></label><label><span>标准配置</span><label><input type="checkbox" id="loadStandardConfig" checked> 自动载入参数配置</label></label>');document.querySelector('#createBusinessMode').onchange=e=>state.creation.mode=e.target.value;document.querySelector('#createLevel').onchange=e=>state.creation.level=e.target.value}
// app.js 在初始化时已绑定原始函数；重新绑定入口，确保增强版联动逻辑生效。
document.querySelector('#createTemplate')&&(document.querySelector('#createTemplate').onclick=event=>{event.preventDefault();openCreateTemplate()});
const baseOpenDesigner=openDesigner;
openDesigner=function(id){baseOpenDesigner(id);ensureTemplateEditingContext();renderFormBuildStep()}
const baseRenderDesignerContext=renderDesigner;
renderDesigner=function(){baseRenderDesignerContext();normalizeDesignerHeader()}
const baseRenderResourceStep=renderResourceStep;
renderResourceStep=function(){baseRenderResourceStep();const area=document.querySelector('.resource-area');if(!area||document.querySelector('.data-architecture-card'))return;area.insertAdjacentHTML('afterbegin','<div class="data-architecture-card"><div><b>本模板的数据档案结构</b><span>一张作业票主记录，后续节点持续追加业务数据</span></div><div class="data-architecture-flow"><em>主表 · 作业票</em><i>→</i><em>风险评估</em><i>→</i><em>安全准备</em><i>→</i><em>交底 / 实施</em><i>→</i><em>验收归档</em></div><small>主表保存编号、作业类型、等级、地点和状态；各节点表单保存本节点填报、签名、附件与审批记录。</small></div>')}
controlPreview=function(c){if(c.group==='layout')return c.type==='分割线'?'<div class="layout-divider"><span>'+c.name+'</span></div>':'<div class="layout-control"><b>'+c.name+'</b><small>'+c.type+'</small></div>';const special={数字输入:'<span class="fake-input">0　　±</span>',日期选择:'<span class="fake-input">📅 请选择日期</span>',时间选择:'<span class="fake-input">◷ 请选择时间</span>',用户选择:'<span class="fake-input">👤 请选择人员</span>',部门选择:'<span class="fake-input">▦ 请选择部门</span>',下拉选择:'<span class="fake-input select-preview">请选择　⌄</span>',级联选择:'<span class="fake-input select-preview">请选择区域　⌄</span>',单选框组:'<span class="radio-preview"><i></i> 选项一　 <i></i> 选项二</span>',多选框组:'<span class="radio-preview"><i class="check"></i> 选项一　 <i class="check"></i> 选项二</span>',图片上传:'<span class="upload-box">＋ 上传图片</span>',文件上传:'<span class="upload-box">＋ 上传文件</span>',手写签名:'<span class="signature-box">✍ 点击签名</span>',气体检测:'<span class="module-box">气体检测项目　检测结果</span>',风险辨识:'<span class="module-box">风险点　管控措施</span>',安全交底:'<span class="module-box">作业步骤　安全防范措施　签名</span>',子表单:'<span class="subtable-box">明细表　＋ 新增一行</span>'};return '<label class="canvas-field-label"><span>'+(c.required?'<i>*</i>':'')+c.name+'</span>'+(special[c.type]||'<span class="fake-input">'+(c.readonly?'系统自动生成':c.placeholder||'请输入')+'</span>')+'</label>'}
const controlIcons={单行输入:'▣',多行输入:'▤',数字输入:'123',开关:'◉',单选框组:'◉',多选框组:'☑',下拉选择:'⌄',级联选择:'☷',日期选择:'▣',时间选择:'◷',文件上传:'⇧',图片上传:'▧',颜色选择:'●',评分:'☆',滑块:'☷',富文本:'▤',链接:'↗',按钮:'▰',文本:'T',提示:'ⓘ',二维码:'▦',条形码:'▥',组织选择:'♙',岗位选择:'♟',用户选择:'♙',角色选择:'♧',设计子表:'▤',省市区域:'⌖',关联表单:'↔',弹窗选择:'▣',电子签章:'✎',手写签名:'✍',定位:'⌖',Iframe:'□',数字公式:'ƒ',日期公式:'ƒ',关联查询:'⌕',创建人员:'♙',创建时间:'◷',修改人员:'♙',修改时间:'◷',所属组织:'▦',所属岗位:'♟',单据组件:'▤',分组标题:'▤',分割线:'—',折叠面板:'⌄',标签面板:'▥',步骤条:'1→2',栅格容器:'▦',卡片容器:'▣',表格容器:'▤'};
controlLibrary=function(){return controlGroups.filter(g=>g[1]!=='work').map(g=>`<div class="control-group"><button class="group-toggle" data-group-toggle="${g[1]}"><b>${g[0]}</b><span>⌃</span></button><div class="control-grid" data-group-body="${g[1]}">${g[2].map(x=>`<button draggable="true" data-build-control="${x}" data-control-group="${g[1]}"><i class="control-icon">${controlIcons[x]||'◆'}</i><span>${x}</span></button>`).join('')}</div></div>`).join('')}
const baseComponentPropertyMarkup=componentPropertyMarkup;componentPropertyMarkup=function(control){let html=baseComponentPropertyMarkup(control);const extra={开关:'<div class="attribute-section"><b>开关值</b><label>打开时文本<input value="是"></label><label>关闭时文本<input value="否"></label></div>',用户选择:'<div class="attribute-section"><b>选择范围</b><label>数据范围<select><option>全组织</option><option>指定组织</option></select></label></div>',组织选择:'<div class="attribute-section"><b>组织范围</b><select><option>当前组织</option><option>指定组织</option></select></div>',岗位选择:'<div class="attribute-section"><b>岗位范围</b><select><option>当前组织岗位</option><option>全部岗位</option></select></div>',角色选择:'<div class="attribute-section"><b>角色范围</b><select><option>当前组织角色</option><option>全部角色</option></select></div>'};const block=extra[control.type];return block?html.replace('</div></div>',''+block+'</div></div>'):html}
