const defaultConfiguredControls=[
 {id:'risk',name:'风险评估',category:'作业安全',icon:'⚠',description:'配置风险点、风险管控措施、气体检测要求和评估签名。',fields:'作业基本信息、风险点、管控措施、气体检测要求、评估签名',required:true,status:'已启用',updated:'2026-09-08'},
 {id:'gas',name:'气体检测',category:'现场检测',icon:'◉',description:'配置检测人、检测频次、重复周期、检测项目和检测结果。',fields:'检测人、检测频次、重复周期、检测项目、检测数值、检测结果',required:false,status:'已启用',updated:'2026-09-08'},
 {id:'measure',name:'安全措施确认',category:'作业安全',icon:'✓',description:'逐项确认安全措施是否落实，支持不涉及原因和确认签名。',fields:'安全措施清单、落实状态、不涉及原因、确认签名',required:true,status:'已启用',updated:'2026-09-08'},
 {id:'briefing',name:'安全交底',category:'交底确认',icon:'▤',description:'配置作业步骤、安全防范措施、周边危险禁入区域和交底签名。',fields:'作业步骤、安全防范措施、周边危险禁入区域、交底签名',required:true,status:'已启用',updated:'2026-09-08'},
 {id:'receive',name:'接收交底',category:'交底确认',icon:'✍',description:'展示前序交底内容，由作业人员进行接收确认并签字。',fields:'作业基本信息、风险管控内容、接收确认、接收签字',required:true,status:'已启用',updated:'2026-09-08'},
 {id:'supervision',name:'监管确认',category:'现场监管',icon:'◈',description:'施工单位与业主单位依次确认，分别保存意见、时间和签字。',fields:'施工单位确认、业主单位确认、确认意见、确认签字',required:true,status:'已启用',updated:'2026-09-12'},
 {id:'submit',name:'提交验收',category:'验收归档',icon:'◎',description:'记录实际作业时间、收尾事项、现场证据及双方收尾签字。',fields:'实际开始时间、实际完工时间、收尾事项、现场附件、双方签字',required:true,status:'已启用',updated:'2026-09-12'},
 {id:'finish',name:'结束确认',category:'验收归档',icon:'◎',description:'记录实际开始和完成时间、结束标准、现场证据及负责人签字。',fields:'实际开始时间、完成时间、结束标准、现场证据、负责人签字',required:true,status:'已启用',updated:'2026-09-08'},
 {id:'acceptance',name:'验收审批',category:'验收归档',icon:'◆',description:'配置验收资料、验收结果、验收意见和验收签名。',fields:'验收资料、验收结果、验收意见、验收签名',required:true,status:'已启用',updated:'2026-09-08'}
];

let configuredControls=loadConfiguredControls();
let controlKeyword='';
let controlCategory='全部分类';

function loadConfiguredControls(){
 try{const saved=JSON.parse(localStorage.getItem('standaloneConfiguredControls')||'[]');if(Array.isArray(saved)&&saved.length)return saved}catch(e){}
 return defaultConfiguredControls.map(item=>({...item}));
}
function saveConfiguredControls(){localStorage.setItem('standaloneConfiguredControls',JSON.stringify(configuredControls))}
function controlCategories(){return ['全部分类',...new Set(configuredControls.map(item=>item.category))]}
function escapeControlText(value){return String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]))}
function configuredControlCard(item){return `<article class="configured-control-card"><div class="configured-control-icon">${escapeControlText(item.icon)}</div><div class="configured-control-main"><div class="configured-control-title"><h3>${escapeControlText(item.name)}</h3><span class="tag published">${escapeControlText(item.status)}</span></div><p>${escapeControlText(item.description)}</p><div class="configured-control-meta"><span>${escapeControlText(item.category)}</span><span>${item.required?'默认必填':'可选启用'}</span><span>更新于 ${escapeControlText(item.updated)}</span></div><small>包含字段：${escapeControlText(item.fields)}</small></div><div class="configured-control-actions"><button class="secondary" data-control-preview="${item.id}">预览</button><button class="primary" data-control-edit="${item.id}">编辑控件</button></div></article>`}
function renderConfiguredControlLibrary(){
 title.textContent='作业控件库';subtitle.textContent='集中维护流程节点可复用的作业业务控件';
 const visible=configuredControls.filter(item=>(controlCategory==='全部分类'||item.category===controlCategory)&&(`${item.name}${item.description}${item.fields}`.includes(controlKeyword)));
 app.innerHTML=`<section class="control-library-summary"><div><b>${configuredControls.length}</b><span>已配置控件</span></div><div><b>${configuredControls.filter(x=>x.required).length}</b><span>默认必填</span></div><div><b>${controlCategories().length-1}</b><span>业务分类</span></div><p>此处保存的控件作为标准业务组件，在流程编排的节点表单中复用。</p></section><div class="toolbar control-library-toolbar"><div class="toolbar-left"><b>已配置控件</b><span>集中新增、编辑和维护可复用的作业控件。</span></div><div class="toolbar-right"><button class="primary" id="createConfiguredControl">＋ 新增控件</button><select id="controlCategoryFilter">${controlCategories().map(x=>`<option ${x===controlCategory?'selected':''}>${x}</option>`).join('')}</select><label class="search"><input id="controlLibrarySearch" value="${escapeControlText(controlKeyword)}" placeholder="搜索控件名称或字段"></label></div></div><div class="configured-control-list">${visible.length?visible.map(configuredControlCard).join(''):'<div class="empty">没有匹配的作业控件。</div>'}</div>`;
 document.querySelector('#createConfiguredControl').onclick=openCreateConfiguredControl;
 document.querySelector('#controlCategoryFilter').onchange=e=>{controlCategory=e.target.value;renderConfiguredControlLibrary()};
 document.querySelector('#controlLibrarySearch').oninput=e=>{controlKeyword=e.target.value;renderConfiguredControlLibrary()};
 document.querySelectorAll('[data-control-edit]').forEach(button=>button.onclick=()=>openConfiguredControlEditor(button.dataset.controlEdit));
 document.querySelectorAll('[data-control-preview]').forEach(button=>button.onclick=()=>openConfiguredControlPreview(button.dataset.controlPreview));
}
function openCreateConfiguredControl(){
 const categories=controlCategories().slice(1);
 const card=document.querySelector('.modal-card');card.className='modal-card control-editor-dialog';
 document.querySelector('#modalBody').innerHTML=`<h2>新增作业控件</h2><p class="version-intro">创建后将保存到作业控件库，可继续编辑并用于模板设计。</p><div class="configured-control-form"><label><span><i>*</i>控件名称</span><input id="newControlName" placeholder="请输入控件名称"></label><label><span><i>*</i>业务分类</span><input id="newControlCategory" list="controlCategoryOptions" placeholder="选择或输入分类"><datalist id="controlCategoryOptions">${categories.map(x=>`<option value="${escapeControlText(x)}">`).join('')}</datalist></label><label class="wide"><span><i>*</i>控件说明</span><textarea id="newControlDescription" rows="3" placeholder="说明控件的用途和使用场景"></textarea></label><label class="wide"><span><i>*</i>包含字段</span><textarea id="newControlFields" rows="3" placeholder="例如：检查结果、补充说明、确认签字"></textarea><small>多个字段使用顿号分隔。</small></label><label><span>控件图标</span><input id="newControlIcon" value="◇" maxlength="2"></label><label><span>默认校验</span><select id="newControlRequired"><option value="true">默认必填</option><option value="false">可选启用</option></select></label></div><div class="dialog-footer"><button class="ghost" id="cancelCreateControl">取消</button><button class="primary" id="saveCreateControl">创建控件</button></div>`;
 openModalShell();document.querySelector('#cancelCreateControl').onclick=closeModalShell;document.querySelector('#newControlName').focus();
 document.querySelector('#saveCreateControl').onclick=()=>{const name=document.querySelector('#newControlName').value.trim(),category=document.querySelector('#newControlCategory').value.trim(),description=document.querySelector('#newControlDescription').value.trim(),fields=document.querySelector('#newControlFields').value.trim();if(!name||!category||!description||!fields)return toast('请完整填写控件名称、业务分类、说明和包含字段');const id=`custom-${Date.now()}`;configuredControls.unshift({id,name,category,icon:document.querySelector('#newControlIcon').value.trim()||'◇',description,fields,required:document.querySelector('#newControlRequired').value==='true',status:'已启用',updated:new Date().toISOString().slice(0,10),custom:true});saveConfiguredControls();controlCategory='全部分类';controlKeyword='';closeModalShell();renderConfiguredControlLibrary();toast('新控件已添加到作业控件库')};
}
function openConfiguredControlEditor(id){
 const item=configuredControls.find(control=>control.id===id);if(!item)return;
 const card=document.querySelector('.modal-card');card.className='modal-card control-editor-dialog';
 document.querySelector('#modalBody').innerHTML=`<h2>编辑作业控件</h2><p class="version-intro">修改后的配置会保存在作业控件库，供流程节点复用。</p><div class="configured-control-form"><label><span><i>*</i>控件名称</span><input id="configuredControlName" value="${escapeControlText(item.name)}"></label><label><span><i>*</i>业务分类</span><select id="configuredControlCategory">${controlCategories().slice(1).map(x=>`<option ${x===item.category?'selected':''}>${x}</option>`).join('')}</select></label><label class="wide"><span><i>*</i>控件说明</span><textarea id="configuredControlDescription" rows="3">${escapeControlText(item.description)}</textarea></label><label class="wide"><span><i>*</i>包含字段</span><textarea id="configuredControlFields" rows="3">${escapeControlText(item.fields)}</textarea><small>多个字段使用顿号分隔。</small></label><label><span>默认校验</span><select id="configuredControlRequired"><option value="true" ${item.required?'selected':''}>默认必填</option><option value="false" ${item.required?'':'selected'}>可选启用</option></select></label><label><span>控件状态</span><select id="configuredControlStatus"><option ${item.status==='已启用'?'selected':''}>已启用</option><option ${item.status==='已停用'?'selected':''}>已停用</option></select></label></div><div class="dialog-footer"><button class="ghost" id="cancelConfiguredControl">取消</button><button class="primary" id="saveConfiguredControl">保存配置</button></div>`;
 openModalShell();document.querySelector('#cancelConfiguredControl').onclick=closeModalShell;
 document.querySelector('#saveConfiguredControl').onclick=()=>{const name=document.querySelector('#configuredControlName').value.trim(),description=document.querySelector('#configuredControlDescription').value.trim(),fieldsValue=document.querySelector('#configuredControlFields').value.trim();if(!name||!description||!fieldsValue)return toast('请完整填写控件名称、说明和包含字段');Object.assign(item,{name,description,fields:fieldsValue,category:document.querySelector('#configuredControlCategory').value,required:document.querySelector('#configuredControlRequired').value==='true',status:document.querySelector('#configuredControlStatus').value,updated:new Date().toISOString().slice(0,10)});saveConfiguredControls();closeModalShell();renderConfiguredControlLibrary();toast('作业控件配置已保存')};
}
function openConfiguredControlPreview(id){const item=configuredControls.find(control=>control.id===id);if(!item)return;document.querySelector('#modalBody').innerHTML=`<span class="tag published">控件预览</span><h2>${escapeControlText(item.name)}</h2><p>${escapeControlText(item.description)}</p><div class="job-preview-form"><div class="preview-section"><b>${escapeControlText(item.category)}</b><span>${item.required?'默认必填':'可选启用'}</span></div>${item.fields.split(/[、,]/).filter(Boolean).map(field=>`<div class="preview-row"><label>${escapeControlText(field.trim())}</label><div class="preview-placeholder">请配置${escapeControlText(field.trim())}</div></div>`).join('')}</div><div class="dialog-footer"><button class="primary" id="closeConfiguredPreview">关闭</button></div>`;openModalShell();document.querySelector('#closeConfiguredPreview').onclick=closeModalShell}

document.querySelectorAll('.sidebar nav button').forEach(button=>button.onclick=()=>{document.querySelector('.sidebar nav .active')?.classList.remove('active');button.classList.add('active');state.page=button.dataset.page;if(state.page==='center')centerView();else if(state.page==='controls')renderConfiguredControlLibrary();else simpleList(state.page)});
if(new URLSearchParams(location.search).get('page')==='controls')renderConfiguredControlLibrary();
