const standardNodeDefinitions=[
 {name:'风险评估',type:'填报+确认',group:'风险评估组件组',desc:'风险点、管控措施、是否气体检测',fields:['作业基本信息','风险点与管控措施','气体检测要求','评估签名'],output:'need_gas_detection'},
 {name:'气体检测',type:'填报',group:'气体检测组件组',desc:'按风险评估配置执行检测',fields:['检测项目','检测数值','检测人','检测结果'],condition:'need_gas_detection = true',output:'gas_detection_passed'},
 {name:'安全措施确认',type:'填报+确认',group:'安全措施组件组',desc:'逐项落实安全措施并签名',fields:['措施清单','落实状态','确认人','确认签名'],output:'measures_confirmed'},
 {name:'安全交底',type:'填报+签名',group:'安全交底组件组',desc:'发布作业步骤和安全防范内容',fields:['作业步骤','安全防范措施','危险禁入区域','交底签名'],output:'briefing_published'},
 {name:'接收交底',type:'确认+签名',group:'接收交底组件组',desc:'只读接收前序交底内容',fields:['作业基本信息','作业步骤','风险和管控措施','接收签字'],output:'briefing_received'},
 {name:'提交验收',type:'填报+签名',group:'结束确认组件组',desc:'填写结束确认标准和现场证据',fields:['实际完成时间','结束确认标准','作业视频/照片','负责人签字'],output:'acceptance_submitted'},
 {name:'验收审批',type:'审批',group:'验收审批组件组',desc:'审核验收资料并归档',fields:['验收资料','验收意见','验收签名'],output:'acceptance_approved'}
];
const standardFlowSeed=[
 {name:'作业申请',handler:'作业负责人',type:'发起',formGroup:'作业申请表',nodeType:'填报',fields:['作业基本信息','人员与地点','附件']},
 {name:'风险评估',handler:'风险评估人',type:'填报',formGroup:'风险评估组件组',nodeType:'填报+确认',fields:['作业基本信息','风险点与管控措施','气体检测要求','评估签名'],output:'need_gas_detection'},
 {name:'气体检测',handler:'检测人员',type:'条件填报',formGroup:'气体检测组件组',nodeType:'填报',fields:['检测项目','检测数值','检测人','检测结果'],condition:'need_gas_detection = true',output:'gas_detection_passed'},
 {name:'安全措施确认',handler:'安全交底人',type:'填报',formGroup:'安全措施组件组',nodeType:'填报+确认',fields:['措施清单','落实状态','确认人','确认签名'],output:'measures_confirmed'},
 {name:'安全交底',handler:'交底人',type:'签名确认',formGroup:'安全交底组件组',nodeType:'填报+签名',fields:['作业步骤','安全防范措施','危险禁入区域','交底签名'],output:'briefing_published'},
 {name:'接收交底',handler:'作业人员',type:'签名确认',formGroup:'接收交底组件组',nodeType:'确认+签名',fields:['作业基本信息','作业步骤','风险和管控措施','接收签字'],output:'briefing_received'},
 {name:'作业审批',handler:'安全管理部门',type:'审批',formGroup:'作业审批表',nodeType:'审批',fields:['完整作业资料','审批意见','审批签名']},
 {name:'提交验收',handler:'作业负责人',type:'填报',formGroup:'结束确认组件组',nodeType:'填报+签名',fields:['实际完成时间','结束确认标准','作业视频/照片','负责人签字'],output:'acceptance_submitted'},
 {name:'验收审批',handler:'验收负责人',type:'审批',formGroup:'验收审批组件组',nodeType:'审批',fields:['验收资料','验收意见','验收签名']},
 {name:'流程归档',handler:'系统自动完成',type:'结束',formGroup:'归档记录',nodeType:'自动处理',fields:['版本快照','完整操作日志']}
];
function ensureStandardFlow(){if(state.standardFlowSeeded)return;nodes=standardFlowSeed.map(node=>({...node,fields:[...node.fields]}));state.selectedNode=0;state.standardFlowSeeded=true}
function standardNodeButton(def){return `<button class="standard-node" data-standard-node="${def.name}" data-node="${def.name}"><i>▣</i><span><b>${def.name}</b><span>${def.type} · ${def.group}</span></span></button>`}
function nodePropertyMarkup(node){const fields=node.fields||[];const rule=node.condition?`<div class="node-flow-rule"><b>启用条件</b><div class="rule-card"><b>满足条件时执行</b><span>${node.condition}</span></div><select id="nodeCondition"><option>${node.condition}</option><option>始终执行</option><option>gas_detection_passed = true</option></select></div>`:`<div class="node-flow-rule"><b>完成后流转</b><div class="rule-card"><b>节点完成条件</b><span>${node.nodeType==='审批'?'审批意见和审批结果必填':'节点表单校验通过并完成签名'}</span></div></div>`;return `<div class="properties"><label>节点名称<input id="nodeName" value="${node.name}"></label><label>节点处理人<select><option>${node.handler}</option><option>指定成员</option><option>发起者本人</option><option>表单变量</option><option>逐级审批</option></select></label><div class="node-form-binding"><b>节点表单</b><div class="binding-card"><b>${node.formGroup||'未绑定标准组件组'}</b><span>${node.nodeType||node.type} · ${fields.length} 项填报内容</span><div class="binding-tags">${fields.map(field=>`<em>${field}</em>`).join('')}</div></div><select id="nodeFormGroup"><option>${node.formGroup||'请选择组件组'}</option>${standardNodeDefinitions.map(def=>`<option>${def.group}</option>`).join('')}<option>自定义节点表单</option></select><div class="binding-actions"><button id="editNodeForm" type="button">查看/调整节点表单</button></div><div class="node-form-note">前序节点数据会自动带入；本节点新增内容提交后写入对应模块，供后续节点读取。</div></div>${rule}<label><input type="checkbox" checked> 节点表单校验通过后才可提交</label><label><input type="checkbox" checked> 记录填报人与签名时间</label><button class="danger-text" id="removeNode">删除当前节点</button><div class="attribute-actions"><button class="primary" id="saveNodeBinding">保存节点配置</button></div></div>`}
flowDesigner=function(){ensureStandardFlow();const current=nodes[state.selectedNode]||nodes[0];return `<div class="flow-toolbar"><button>↶</button><button>↷</button><span>流程编排 · 节点表单与流转规则</span><button>⊟ 对齐</button><button>⊙ 适应画布</button><b>100%</b></div><div class="designer flow-replica"><aside class="panel"><div class="panel-title"><h3>流程节点</h3><p>节点不仅审核，还可以填报和签名</p></div><div class="flow-library"><b>通用节点</b>${['审批节点','办理节点','条件分支','并行审批'].map(x=>`<button data-node="${x}">＋ ${x}</button>`).join('')}<div class="standard-node-library"><div class="library-caption"><b>标准业务组件组</b><span>由参数配置统一维护，拖入节点即可复用</span></div>${standardNodeDefinitions.map(standardNodeButton).join('')}</div></div></aside><section class="canvas"><div class="canvas-top"><div><b>${state.template.name}标准作业流程</b><small>　节点表单与流转规则</small></div><span><i class="status-dot"></i> 草稿　<button class="ghost" id="autoLayout">自动布局</button></span></div><div class="flow-canvas grid-bg"><div class="flow-track">${nodes.map((node,index)=>`${index?'<span class="flow-arrow">→</span>':''}<article class="flow-node ${state.selectedNode===index?'selected':''}" data-flow-node="${index}" data-standard-node="${node.formGroup&&node.formGroup.includes('组件组')?'true':'false'}"><i>${node.type}</i><b>${node.name}</b><span class="node-badge">${node.nodeType||'节点'}</span><span>${node.handler}</span>${node.formGroup?`<span>${node.formGroup}</span>`:''}${node.condition?`<small class="node-condition">条件：${node.condition}</small>`:''}</article>`).join('')}</div></div></section><aside class="panel"><div class="panel-title"><h3>节点配置</h3><p>处理人、节点表单、字段权限和流转条件</p></div>${nodePropertyMarkup(current)}</aside></div>`}
const baseRenderNodeFormStage=renderFormBuildStep;renderFormBuildStep=function(){baseRenderNodeFormStage();const title=document.querySelector('.designer-head h1');const subtitle=document.querySelector('.designer-head p');if(title)title.textContent='节点表单设计';if(subtitle)subtitle.textContent='配置申请、评估、交底、验收等各流程节点的填报内容'}
const bindDesignerBeforeNodeForms=bindDesigner;bindDesigner=function(){bindDesignerBeforeNodeForms();if(state.mode!=='flow')return;document.querySelectorAll('[data-standard-node]').forEach(button=>button.onclick=()=>{const def=standardNodeDefinitions.find(item=>item.name===button.dataset.standardNode);if(!def)return;nodes.splice(nodes.length-1,0,{...def,fields:[...def.fields],type:def.type,nodeType:def.type,handler:'待配置处理人'});state.selectedNode=nodes.length-2;renderDesigner();toast(`${def.name}组件组已添加到流程`)});document.querySelector('#nodeFormGroup')?.addEventListener('change',event=>{const selected=standardNodeDefinitions.find(item=>item.group===event.target.value);if(!selected)return;Object.assign(nodes[state.selectedNode],{formGroup:selected.group,fields:[...selected.fields],nodeType:selected.type,output:selected.output,condition:selected.condition});renderDesigner();toast(`已绑定${selected.group}`)});document.querySelector('#saveNodeBinding')?.addEventListener('click',()=>toast(`节点“${nodes[state.selectedNode].name}”的表单与流转配置已保存`));document.querySelector('#editNodeForm')?.addEventListener('click',()=>toast('节点表单可在表单设计阶段继续调整，节点权限将在此处覆盖'))}
