let publishPreviewDevice='pc';
let publishPreviewOptions={progress:true,operations:true,handler:true,time:true,opinion:true,attachment:true};

document.addEventListener('click',event=>{if(!event.target.closest('#publishNow'))return;setTimeout(()=>{if(state.template?.status!=='已发布')return;try{const published=JSON.parse(localStorage.getItem('safePublishedWorkTemplates')||'[]');localStorage.setItem('safePublishedWorkTemplates',JSON.stringify([...new Set([...published,state.template.name])]))}catch(_){ }},0)});

function publishProgress(){const previewNodes=nodes.slice(0,5);return `<div class="runtime-progress">${previewNodes.map((n,i)=>`<div class="runtime-step ${i<2?'done':i===2?'current':''}"><span>${i<2?'✓':i+1}</span><b>${n.name}</b><small>${publishPreviewOptions.handler?n.handler:''}${publishPreviewOptions.time&&i<2?'<br>08-29 14:2'+i:''}</small></div>`).join('')}</div>`}
function publishOperations(){const rows=[['提交申请','王安全','提交动火作业申请并完成风险辨识','08-29 14:20'],['单位初审','张建国','审批通过，安全措施已确认','08-29 14:28'],['安全审批','李安全','当前待审批','等待处理']];return `<div class="runtime-operations"><h3>操作记录 <span>全部 ${rows.length}</span></h3>${rows.map((x,i)=>`<article class="${i===rows.length-1?'current':''}"><i>${i+1}</i><div><b>${x[0]}</b><time>${publishPreviewOptions.time?x[3]:''}</time><strong>${x[1]}</strong>${publishPreviewOptions.opinion?`<p>${x[2]}</p>`:''}${publishPreviewOptions.attachment&&i===0?'<a>查看附件（2）</a>':''}</div></article>`).join('')}</div>`}
function publishFormBody(){const data=canvasControls.length?canvasControls.filter(c=>c.group!=='layout').slice(0,10):fields.slice(0,8).map(f=>({name:f.name,type:f.type,required:f.required==='必填'}));return `<div class="runtime-form"><div class="runtime-form-head"><div><span>作业状态</span><b>安全审批中</b></div><div><span>作业编号</span><b>ZY20260829001</b></div><div><span>当前处理人</span><b>安全管理部门</b></div></div><section><h3>${state.template.name}申请信息</h3><div class="runtime-field-grid">${data.map(c=>`<div class="runtime-field"><span>${c.name}</span><b>${c.readonly?'系统自动生成':c.placeholder||c.type||'已填写'}</b></div>`).join('')}</div></section><section><h3>风险与安全措施</h3><div class="measure-list"><p>✓ 作业区域已隔离并设置安全警示</p><p>✓ 动火分析及气体检测结果合格</p><p>✓ 监护人员、消防器材已落实</p></div></section><section><h3>现场附件</h3><div class="attachment-list"><span>▧ 作业方案.pdf</span><span>▧ 现场照片.jpg</span></div></section></div>`}
function publishRuntimePreview(){return `<div class="runtime-preview ${publishPreviewDevice==='mobile'?'mobile':''}">${publishPreviewOptions.progress?`<div class="runtime-progress-card"><h3>流程进度</h3>${publishProgress()}</div>`:''}<div class="runtime-main">${publishFormBody()}${publishPreviewOptions.operations?publishOperations():''}</div></div>`}

function renderPublishStep(){const invalid=nodes.filter(n=>n.type!=='发起'&&n.type!=='结束'&&(n.handler==='待配置处理人'||!n.handler));title.textContent=`${state.template.name} · 发布预览`;subtitle.textContent='预览最终作业详情页并完成发布检查';app.innerHTML=`<div class="build-shell publish-shell"><div class="build-top"><div class="build-brand"><span>${state.creation?.icon||'安'}</span><b>${state.template.name}</b></div>${buildSteps(5)}<div class="actions"><button class="ghost" id="publishPrev">上一步</button><button class="primary" id="publishNow">发布应用</button><button class="ghost" id="publishClose">关闭</button></div></div><section class="publish-page"><div class="publish-summary compact"><span class="publish-icon">✓</span><div><h2>发布预览与检查</h2><p>表单、流程和系统操作日志已组合为最终作业详情页。</p></div><div class="device-switch"><button class="${publishPreviewDevice==='pc'?'active':''}" data-device="pc">PC端</button><button class="${publishPreviewDevice==='mobile'?'active':''}" data-device="mobile">移动端</button></div></div><div class="publish-layout"><aside class="preview-options"><h3>预览设置</h3>${[['progress','流程进度'],['operations','操作记录'],['handler','处理人'],['time','处理时间'],['opinion','操作意见'],['attachment','相关附件']].map(x=>`<label><input type="checkbox" data-preview-option="${x[0]}" ${publishPreviewOptions[x[0]]?'checked':''}> ${x[1]}</label>`).join('')}<hr><h3>发布检查</h3><p class="check-ok">✓ 表单字段已保存</p><p class="check-ok">✓ 流程表单已绑定</p><p class="${invalid.length?'check-warn':'check-ok'}">${invalid.length?'!':'✓'} 审批人${invalid.length?'待配置':'已配置'}</p><p class="check-ok">✓ 流程连线完整</p></aside><div id="runtimePreviewHost">${publishRuntimePreview()}</div></div></section></div>`;document.querySelector('#publishPrev').onclick=()=>{state.mode='flow';renderDesigner()};document.querySelector('#publishClose').onclick=centerView;document.querySelectorAll('[data-device]').forEach(b=>b.onclick=()=>{publishPreviewDevice=b.dataset.device;renderPublishStep()});document.querySelectorAll('[data-preview-option]').forEach(c=>c.onchange=()=>{publishPreviewOptions[c.dataset.previewOption]=c.checked;document.querySelector('#runtimePreviewHost').innerHTML=publishRuntimePreview()});document.querySelector('#publishNow').onclick=()=>{if(invalid.length||nodes.length<3)return toast('内容不完善：请配置审批人并确保流程连线完整');state.template.status='已发布';toast('发布成功，最终详情页已生成');setTimeout(centerView,900)}}
