const workTypes=[
  {code:'WX-01',name:'有限空间作业',group:'危险作业',level:'分级管控',plan:true,caseRule:'条件触发',enabled:true},
  {code:'WX-02',name:'高处作业',group:'危险作业',level:'四级',plan:true,caseRule:'条件触发',enabled:true},
  {code:'WX-03',name:'吊装作业',group:'危险作业',level:'三级',plan:true,caseRule:'条件触发',enabled:true},
  {code:'WX-04',name:'临时用电作业',group:'危险作业',level:'不分级',plan:true,caseRule:'条件触发',enabled:true},
  {code:'WX-05',name:'动土作业',group:'危险作业',level:'不分级',plan:true,caseRule:'条件触发',enabled:true},
  {code:'WX-06',name:'断路作业',group:'危险作业',level:'不分级',plan:true,caseRule:'条件触发',enabled:true},
  {code:'WX-07',name:'井下爆破作业',group:'危险作业',level:'分级管控',plan:true,caseRule:'条件触发',enabled:true},
  {code:'WX-08',name:'露天爆破作业',group:'危险作业',level:'分级管控',plan:true,caseRule:'条件触发',enabled:true},
  {code:'WX-09',name:'盲板抽堵作业',group:'危险作业',level:'不分级',plan:true,caseRule:'条件触发',enabled:true},
  {code:'WX-10',name:'支护作业',group:'危险作业',level:'分级管控',plan:true,caseRule:'条件触发',enabled:true},
  {code:'WX-11',name:'探放水作业',group:'危险作业',level:'分级管控',plan:true,caseRule:'条件触发',enabled:true},
  {code:'WX-12',name:'空区治理作业',group:'危险作业',level:'分级管控',plan:true,caseRule:'条件触发',enabled:true},
  {code:'JX-01',name:'交叉作业',group:'交叉作业',level:'不分级',plan:true,caseRule:'强制',enabled:true},
  {code:'WD-01',name:'基坑工程',group:'危大工程',level:'分级管控',plan:true,caseRule:'强制',enabled:true},
  {code:'WD-02',name:'模板及支撑工程',group:'危大工程',level:'分级管控',plan:true,caseRule:'强制',enabled:true},
  {code:'WD-03',name:'起重机械安拆工程',group:'危大工程',level:'分级管控',plan:true,caseRule:'强制',enabled:true},
  {code:'WD-04',name:'脚手架工程',group:'危大工程',level:'分级管控',plan:true,caseRule:'强制',enabled:true},
  {code:'WD-05',name:'拆除工程',group:'危大工程',level:'分级管控',plan:true,caseRule:'强制',enabled:true}
];

const content=document.querySelector('#content');let activePage='overview';let typeFilter='';let search='';
let briefingItems=['明确作业内容、地点、时间和作业范围','核对作业人员资质和个人防护用品','交底现场风险、安全措施及应急处置要求'];
let finishItems=['作业人员全部撤离作业区域','工器具、材料和临时设施已清点','作业现场恢复，遗留风险已交接'];
let riskMeasures=['作业前强制通风并检测气体浓度','作业过程中持续通风和检测','现场配备应急救援器材'];
const ruleRows=(items)=>items.map(x=>`<div class="setting-row"><div class="setting-copy"><b>${x[0]}</b><small>${x[1]}</small></div>${x[2]}</div>`).join('');
const sw=(on=true)=>`<button class="switch ${on?'on':''}" aria-label="开关" aria-pressed="${on}"></button>`;

function overview(){return `<div class="section-head"><div><h2>配置总览</h2><p>当前发布版本 V1.0.01 · 2026-09-06 14:30</p></div><span class="status on">配置已生效</span></div>
<div class="stats"><div class="stat"><small>作业类型</small><strong>18</strong><span><i>18</i> 项已启用</span></div><div class="stat"><small>危险作业</small><strong>12</strong><span>包含井下/露天爆破</span></div><div class="stat"><small>危大工程</small><strong>5</strong><span>全部强制一件一案</span></div><div class="stat"><small>待完善项</small><strong>2</strong><span>需补充规则或范围</span></div></div>
<div class="grid-two"><div class="card"><div class="card-head"><b>核心规则状态</b><span>最近检查：刚刚</span></div><div class="rule-list">
${[['作业类型','18种作业已按危险作业、交叉作业、危大工程分类','已生效'],['作业计划','支持计划多明细批量转作业票','已生效'],['一件一案','13种作业适用，危大工程强制关联','已生效'],['交叉作业','时间、空间、设备及隔离范围冲突触发','待完善']].map((x,i)=>`<div class="rule-item"><span class="rule-icon">${['▤','▣','◇','⨝'][i]}</span><div><b>${x[0]}</b><small>${x[1]}</small></div><span class="status ${i===3?'warn':'on'}">${x[2]}</span></div>`).join('')}</div></div>
<div class="card"><div class="card-head"><b>待办提醒</b><button class="action" data-page-jump="types">查看全部</button></div><div class="notice-list"><div class="notice"><b>需确认一件一案触发阈值</b><p>作业人数、持续时间和外委单位触发值待补充。</p><time>2026-09-06</time></div><div class="notice"><b>交叉作业空间判定范围</b><p>需按厂区、采区或设备类型补充默认范围。</p><time>2026-09-06</time></div></div></div></div>`}

function typesPage(){const rows=workTypes.filter(x=>(!typeFilter||x.group===typeFilter)&&(!search||`${x.name}${x.code}`.includes(search)));return `<div class="section-head"><div><h2>作业类型配置</h2><p>管理18种作业的分类、等级、计划关联和一件一案适用规则</p></div><div class="section-actions"><button class="button secondary" id="exportBtn">导出配置</button><button class="button primary" id="addTypeBtn">＋ 新增类型</button></div></div>
<div class="callout blue"><b>范围说明</b><span>常规作业不纳入本页18种作业类型；作业计划和一件一案作为独立业务对象，在本页仅配置关联规则。</span></div>
<div class="toolbar"><label class="search"><input id="typeSearch" value="${search}" placeholder="搜索作业名称或编码"></label><select id="typeGroup"><option value="">全部分类</option>${['危险作业','交叉作业','危大工程'].map(x=>`<option ${x===typeFilter?'selected':''}>${x}</option>`).join('')}</select><span class="count">共 ${rows.length} 项</span></div>
${rows.length?`<table><thead><tr><th>编码</th><th>作业类型</th><th>所属分类</th><th>作业等级</th><th>计划关联</th><th>一件一案</th><th>状态</th><th>操作</th></tr></thead><tbody>${rows.map(x=>`<tr><td class="type-code">${x.code}</td><td><b>${x.name}</b></td><td><span class="tag ${x.group==='危大工程'?'purple':x.group==='交叉作业'?'red':''}">${x.group}</span></td><td>${x.level}</td><td>${x.plan?'允许':'不允许'}</td><td>${x.caseRule}</td><td><span class="status ${x.enabled?'on':'off'}">${x.enabled?'启用':'停用'}</span></td><td><button class="action edit-type" data-code="${x.code}">编辑</button><button class="action toggle-type" data-code="${x.code}">${x.enabled?'停用':'启用'}</button></td></tr>`).join('')}</tbody></table><div class="pagination"><span>共 ${rows.length} 条</span><button>‹</button><button class="active">1</button><button>›</button></div>`:`<div class="empty"><b>未找到匹配的作业类型</b><span>请调整搜索词或分类条件</span></div>`}`}

function settingsPage(kind){const data={
plan:{title:'作业计划规则',desc:'配置计划审批、发布、转票及冲突检查规则',call:'计划是作业票的可选来源。启用计划后，仍可按作业类型规则允许计划外直接申请。',blocks:[['基础规则',[["启用作业计划","显示作业计划业务菜单并允许编制计划",sw()],['计划审批','计划发布前必须完成审批',sw()],['发布后变更','时间、地点、作业类型等受控字段变更时重新审批','<select class="select"><option>变更审批</option><option>禁止修改</option></select>']]],['计划转票',[["允许批量转票","选择多条计划明细批量生成作业票",sw()],['默认生成方式','一条计划明细默认生成一张作业票','<select class="select"><option>一明细一票</option><option>手动拆分</option></select>'],['受控字段','计划带入的作业类型、地点和时间不允许直接修改','<button class="button secondary">配置字段</button>']]],['冲突与完成',[["启用冲突检查","检查作业时间、地点、设备和隔离范围",sw()],['冲突处理','命中强制条件时创建或关联交叉作业','<select class="select"><option>提醒并阻断</option><option>仅提醒</option></select>'],['计划完成条件','计划下所有有效作业票完成后才能完成','<select class="select"><option>全部作业票完成</option></select>']]]]},
case:{title:'一件一案规则',desc:'配置适用范围、触发条件、分级审批和归档标准',call:'一件一案是独立业务对象，不替代作业票。一个案件可关联一张或多张作业票。',blocks:[['准入与适用范围',[["启用一件一案","显示一件一案菜单并启用准入校验",sw()],['适用作业','13种作业已配置为可选、条件触发或强制','<button class="button secondary" data-page-jump="types">查看13种</button>'],['危大工程','5种危大工程必须建立一件一案','<span class="status on">强制</span>']]],['条件触发',[["涉及多种危险作业","同一作业任务涉及的危险作业数量",'<span><input class="mini-input" value="2"> 种及以上</span>'],['作业人数','达到指定人数时触发一件一案','<span><input class="mini-input" placeholder="待定"> 人及以上</span>'],['外委作业','由外委单位实施且命中适用作业时触发',sw()]]],['分级与归档',[["分级方式","按特殊作业类型、数量和人员规模评定",'<select class="select"><option>A / B / C 三级</option></select>'],['人员变更','作业过程中更换人员需要办理变更审批',sw()],['归档条件','关联票全部完成、过程及收尾材料齐全','<button class="button secondary">配置清单</button>']]]]},
cross:{title:'交叉作业规则',desc:'配置交叉作业的关联数量、自动识别、协同确认和开工控制',call:'交叉作业是18种独立作业类型之一，同时也是处理多项作业相互影响的协同机制。',blocks:[
  ['创建与关联',[
    ['允许人工创建','主动选择相互影响的作业建立交叉作业',sw()],
    ['最少关联数','交叉作业最少应关联的有效作业数量','<span><input class="mini-input" value="2"> 项</span>'],
    ['允许关联范围','危险作业、危大工程及其他有效作业','<button class="button secondary">配置范围</button>']
  ]],
  ['自动识别',[
    ['自动识别交叉风险','在计划编制、作业申请和变更时进行识别',sw()],
    ['时间冲突','作业时间段存在重叠',sw()],
    ['空间冲突','作业区域、设备或隔离范围重叠',sw()],
    ['命中后处理','达到强制条件时必须创建交叉作业','<select class="select"><option>强制创建</option><option>仅提醒</option></select>']
  ]],
  ['协同与开工',[
    ['各作业负责人协同确认','所有关联作业负责人确认共享风险与措施',sw()],
    ['开工联锁','交叉作业审批通过后，关联作业才可开工',sw()],
    ['关联作业变更','时间、地点、人员等变更后重新判断并按规则重审','<select class="select"><option>按影响范围重审</option></select>']
  ]]
]}
}[kind];return `<div class="section-head"><div><h2>${data.title}</h2><p>${data.desc}</p></div><button class="button primary local-save">保存当前配置</button></div><div class="callout blue"><b>业务定位</b><span>${data.call}</span></div>${data.blocks.map(b=>`<section class="setting-block"><div class="setting-title"><div><b>${b[0]}</b><p>规则变更仅对新发起业务生效，历史数据保留原版本</p></div><span class="status on">已启用</span></div><div class="setting-body">${ruleRows(b[1])}</div></section>`).join('')}`}

function overviewLegacy(){return `<div class="legacy-title"><b>作业类型设置</b><small>维护一级作业类型和二级作业类型</small></div>
<div class="table-actions"><button class="button primary" data-action="add-category">＋ 新增一级节点</button></div>
<table><thead><tr><th>排序</th><th>作业类型名称</th><th>状态</th><th>操作</th></tr></thead><tbody>
<tr><td>›　1</td><td><b>危险作业</b><small>一级节点 · 12个二级类型</small></td><td><span class="status on">启用</span></td><td><button class="action">上移</button><button class="action">下移</button><button class="action" data-page-jump="types">查看子级</button><button class="action">编辑</button></td></tr>
<tr><td>›　2</td><td><b>交叉作业</b><small>一级节点 · 1个二级类型</small></td><td><span class="status on">启用</span></td><td><button class="action">上移</button><button class="action">下移</button><button class="action" data-page-jump="cross">规则配置</button><button class="action">编辑</button></td></tr>
<tr><td>›　3</td><td><b>危大工程</b><small>一级节点 · 5个二级类型</small></td><td><span class="status on">启用</span></td><td><button class="action">上移</button><button class="action">下移</button><button class="action" data-page-jump="types">查看子级</button><button class="action">编辑</button></td></tr>
</tbody></table>
<div class="legacy-title"><b>全局业务规则</b><small>适用于所有作业计划、一件一案和18种作业类型</small></div>
<div class="legacy-settings">
${[['作业编号规则','按作业类型＋日期＋流水号自动生成'],['是否需要初审','作业进入风险评估前需完成初审'],['是否必须风险评估','18种作业须完成风险识别和管控措施确认'],['是否必须安全交底','作业人员接收交底并签字后方可开工']].map(x=>`<div class="legacy-row"><b>${x[0]}</b><div class="segmented"><button class="active">开启</button><button>关闭</button></div><p>${x[1]}</p></div>`).join('')}
</div>`}

function riskPage(){return `<div class="section-head"><div><h2>风险内容配置</h2><p>按作业类型、等级维护风险点、安全措施及触发规则</p></div><button class="button primary" data-action="add-risk">＋ 新增风险点</button></div>
<div class="subtabs"><button class="active">有限空间</button><button>高处作业</button><button>吊装作业</button><button>临时用电</button><button>动土作业</button><button>更多…</button></div>
<div class="risk-layout"><aside class="risk-points"><button class="active">窒息与中毒风险</button><button>易燃易爆气体</button><button>机械伤害</button><button>人员误入</button><button data-action="add-risk">＋ 新增风险点</button></aside><div class="risk-detail"><div class="risk-detail-head"><div><b>窒息与中毒风险</b><small>适用等级：全部</small></div><div><button class="button secondary" data-action="add-measure">新增措施</button> <button class="button secondary" data-action="risk-rule">编辑触发规则</button></div></div><table><thead><tr><th>序号</th><th>安全措施</th><th>适用等级</th><th>是否必填</th><th>操作</th></tr></thead><tbody>${riskMeasures.map((x,i)=>`<tr><td>${i+1}</td><td>${x}</td><td>全部</td><td>是</td><td><button class="action" data-action="edit-measure" data-index="${i}">编辑</button><button class="action" data-action="delete-measure" data-index="${i}">删除</button></td></tr>`).join('')}</tbody></table></div></div>`}

function briefingPage(){return contentListPage('安全交底配置','按作业类型和等级维护作业前、作业中、作业后的交底内容',briefingItems,'briefing')}
function finishPage(){return contentListPage('结束确认标准','按作业类型和等级维护完工、清场、隔离解除及验收标准',finishItems,'finish')}
function contentListPage(title,desc,items,kind){return `<div class="section-head"><div><h2>${title}</h2><p>${desc}</p></div><button class="button primary" data-action="add-content" data-kind="${kind}">＋ 新增</button></div><div class="subtabs"><button class="active">有限空间</button><button>高处作业</button><button>吊装作业</button><button>临时用电</button><button>更多…</button></div><div class="toolbar"><select><option>全部等级</option></select><span class="count">共 ${items.length} 条</span></div><table><thead><tr><th>序号</th><th>内容</th><th>适用范围</th><th>状态</th><th>操作</th></tr></thead><tbody>${items.map((x,i)=>`<tr><td>${i+1}</td><td>${x}</td><td>有限空间 · 全部等级</td><td><span class="status on">启用</span></td><td><button class="action" data-action="edit-content" data-kind="${kind}" data-index="${i}">编辑</button><button class="action" data-action="delete-content" data-kind="${kind}" data-index="${i}">删除</button></td></tr>`).join('')}</tbody></table>`}

function render(){const pages={overview:overviewLegacy,types:typesPage,risk:riskPage,briefing:briefingPage,finish:finishPage};content.innerHTML=pages[activePage]?pages[activePage]():settingsPage(activePage);bindContent()}
function bindContent(){content.querySelectorAll('[data-page-jump]').forEach(b=>b.onclick=()=>go(b.dataset.pageJump));content.querySelectorAll('.switch').forEach(b=>b.onclick=()=>{b.classList.toggle('on');b.setAttribute('aria-pressed',b.classList.contains('on'));toast('开关状态已更新，发布后生效')});content.querySelectorAll('.segmented button').forEach(b=>b.onclick=()=>{b.parentElement.querySelector('.active')?.classList.remove('active');b.classList.add('active');toast(`已${b.textContent}`)});content.querySelectorAll('.subtabs button').forEach(b=>b.onclick=()=>{b.parentElement.querySelector('.active')?.classList.remove('active');b.classList.add('active');toast(`已切换至${b.textContent}`)});content.querySelectorAll('.risk-points button:not([data-action])').forEach(b=>b.onclick=()=>{b.parentElement.querySelector('.active')?.classList.remove('active');b.classList.add('active');content.querySelector('.risk-detail-head b').textContent=b.textContent;toast(`已切换至${b.textContent}`)});content.querySelectorAll('.local-save').forEach(b=>b.onclick=()=>toast('当前配置已保存为草稿'));content.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>handleAction(b));content.querySelectorAll('.legacy-row+.legacy-row');content.querySelectorAll('tbody .action').forEach(b=>{if(b.onclick)return;if(b.textContent==='上移'||b.textContent==='下移')b.onclick=()=>moveTableRow(b,b.textContent==='上移'?-1:1);else if(b.textContent==='编辑')b.onclick=()=>openConfigForm('编辑配置','名称',b.closest('tr')?.querySelector('b')?.textContent||'');});content.querySelectorAll('.setting-row .button.secondary').forEach(b=>{if(!b.onclick)b.onclick=()=>openRuleDetail(b.textContent.trim())});if(activePage==='types'){document.querySelector('#typeSearch').oninput=e=>{search=e.target.value.trim();render()};document.querySelector('#typeGroup').onchange=e=>{typeFilter=e.target.value;render()};document.querySelector('#addTypeBtn').onclick=()=>openDrawer();document.querySelector('#exportBtn').onclick=()=>toast('作业类型配置已导出');content.querySelectorAll('.edit-type').forEach(b=>b.onclick=()=>openDrawer(workTypes.find(x=>x.code===b.dataset.code)));content.querySelectorAll('.toggle-type').forEach(b=>b.onclick=()=>{const x=workTypes.find(x=>x.code===b.dataset.code);x.enabled=!x.enabled;render();toast(`${x.name}已${x.enabled?'启用':'停用'}，历史作业不受影响`)})}}
function go(page){activePage=page;document.querySelectorAll('.config-nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===page));render()}
document.querySelectorAll('.config-nav button').forEach(b=>b.onclick=()=>go(b.dataset.page));

const layer=document.querySelector('#drawerLayer');
function openDrawer(item){document.querySelector('#drawerTitle').textContent=item?'编辑作业类型':'新增作业类型';document.querySelector('#drawerBody').innerHTML=`<div class="form-grid"><div class="field"><label><i>*</i> 作业编码</label><input id="fCode" value="${item?.code||''}" placeholder="例如 WX-13" ${item?'disabled':''}></div><div class="field"><label><i>*</i> 所属分类</label><select id="fGroup">${['危险作业','交叉作业','危大工程'].map(x=>`<option ${x===item?.group?'selected':''}>${x}</option>`).join('')}</select></div><div class="field full"><label><i>*</i> 作业名称</label><input id="fName" value="${item?.name||''}" placeholder="请输入作业名称"></div><div class="field"><label>作业等级</label><select id="fLevel">${['不分级','三级','四级','分级管控'].map(x=>`<option ${x===item?.level?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>一件一案</label><select id="fCase">${['不适用','可选','条件触发','强制'].map(x=>`<option ${x===item?.caseRule?'selected':''}>${x}</option>`).join('')}</select></div><div class="field full"><label>流程环节</label><div class="check-grid">${['风险评估','安全措施','安全交底','作业审批','现场监护','完工验收'].map(x=>`<label><input type="checkbox" checked>${x}</label>`).join('')}</div></div></div>`;layer.hidden=false;document.querySelector('#drawerSave').onclick=()=>{const code=document.querySelector('#fCode').value.trim(),name=document.querySelector('#fName').value.trim();if(!code||!name)return toast('请完整填写必填项');if(!item&&workTypes.some(x=>x.code===code))return toast('作业编码已存在，请更换');if(item){Object.assign(item,{name,group:document.querySelector('#fGroup').value,level:document.querySelector('#fLevel').value,caseRule:document.querySelector('#fCase').value})}else{workTypes.push({code,name,group:document.querySelector('#fGroup').value,level:document.querySelector('#fLevel').value,caseRule:document.querySelector('#fCase').value,plan:true,enabled:true})}layer.hidden=true;render();toast('作业类型已保存为草稿')};setTimeout(()=>document.querySelector('#fName').focus(),30)}
function openConfigForm(title,label,value='',onSave){document.querySelector('#drawerTitle').textContent=title;document.querySelector('#drawerBody').innerHTML=`<div class="form-grid"><div class="field full"><label><i>*</i> ${label}</label><textarea id="simpleValue" rows="6" placeholder="请输入${label}">${value}</textarea></div><div class="field"><label>适用等级</label><select><option>全部等级</option><option>一级</option><option>二级</option></select></div><div class="field"><label>状态</label><select><option>启用</option><option>停用</option></select></div></div>`;layer.hidden=false;document.querySelector('#drawerSave').onclick=()=>{const v=document.querySelector('#simpleValue').value.trim();if(!v)return toast(`请输入${label}`);onSave?.(v);layer.hidden=true;render();toast(`${title.replace('新增','').replace('编辑','')}已保存为草稿`)};setTimeout(()=>document.querySelector('#simpleValue').focus(),30)}
function openRuleDetail(name){const fields={配置字段:'作业类型、作业地点、计划时间、责任单位、负责人',配置清单:'一件一案审批表、人员信息、安全交底、过程监管、收尾确认',配置范围:'危险作业、危大工程、未完成的关联作业'};openConfigForm(name,'配置内容',fields[name]||'',()=>{})}
function moveTableRow(button,delta){const row=button.closest('tr'),body=row.parentElement,rows=[...body.children],to=rows.indexOf(row)+delta;if(to<0||to>=rows.length)return toast('已在当前顺序边界');delta<0?body.insertBefore(row,rows[to]):body.insertBefore(rows[to],row);toast('排序已调整，发布后生效')}
function handleAction(button){const action=button.dataset.action,index=Number(button.dataset.index),kind=button.dataset.kind;if(action==='add-category')return openConfigForm('新增一级节点','一级节点名称');if(action==='add-risk')return openConfigForm('新增风险点','风险点名称');if(action==='risk-rule')return openConfigForm('编辑触发规则','触发规则','按作业等级及现场风险触发专项方案、升级审批和现场监护');if(action==='add-measure')return openConfigForm('新增安全措施','安全措施','',v=>riskMeasures.push(v));if(action==='edit-measure')return openConfigForm('编辑安全措施','安全措施',riskMeasures[index],v=>riskMeasures[index]=v);if(action==='delete-measure'){riskMeasures.splice(index,1);render();return toast('安全措施已删除（原型数据）')}const list=kind==='briefing'?briefingItems:finishItems,label=kind==='briefing'?'安全交底内容':'结束确认标准';if(action==='add-content')return openConfigForm(`新增${label}`,label,'',v=>list.push(v));if(action==='edit-content')return openConfigForm(`编辑${label}`,label,list[index],v=>list[index]=v);if(action==='delete-content'){list.splice(index,1);render();toast(`${label}已删除（原型数据）`)}}
layer.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>layer.hidden=true);
let toastTimer;function toast(msg){const el=document.querySelector('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2400)}
document.querySelector('#saveAllBtn')?.addEventListener('click',()=>toast('参数版本 V1.0.02 已发布，仅对新业务生效'));
document.querySelector('#historyBtn')?.addEventListener('click',()=>toast('已加载 6 条历史版本记录'));
document.querySelector('#orgSearch').addEventListener('input',e=>{const q=e.target.value.trim();document.querySelectorAll('#orgList button').forEach(b=>b.hidden=!!q&&!b.textContent.includes(q))});
document.querySelectorAll('#orgList button').forEach(b=>b.onclick=()=>{document.querySelector('#orgList .selected')?.classList.remove('selected');b.classList.add('selected');toast(`已切换所属单位：${b.textContent.trim().replace(/^[▾▪]\s*/,'')}`)});
render();
